[INFO] Starting execution.
[INFO] Downloading package list from PyPI ...
[ERROR] (y) This package does not have downloadable releases.
[INFO] (y-nester) This package is up to date.
[INFO] (y-rip) This package is up to date.
[ERROR] (y-serial) Could not extract data from this package. See below for details.
".py" extension not supported.
[INFO] (y-trans) This package is up to date.
[INFO] (y-w) This package is up to date.
[ERROR] (y001fj-nester) This package does not have downloadable releases.
[INFO] (y2b) Data has been updated for this package.
[INFO] (y2t) Data has been updated for this package.
[INFO] (y4m) This package is up to date.
[INFO] (ya-direct-api) This package is up to date.
[INFO] (ya-ecs-ctl) Data has been updated for this package.
[INFO] (ya-ma) Data has been updated for this package.
[INFO] (ya-music-to-tg-channel-downloader-pkg-arsdev) Data has been updated for this package.
[INFO] (ya-speech-key) This package is up to date.
[INFO] (yaacl) This package is up to date.
[INFO] (yaaf) This package is up to date.
[INFO] (yaahn) This package is up to date.
[INFO] (yaak-inject) This package is up to date.
[ERROR] (yaamp) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yaap) Data has been updated for this package.
[INFO] (yaar) Data has been updated for this package.
[INFO] (yabc) Data has been updated for this package.
[INFO] (yabealice-test) This package is up to date.
[INFO] (yabencode) This package is up to date.
[INFO] (yabgp) Data has been updated for this package.
[INFO] (yabmp) This package is up to date.
[INFO] (yabn) This package is up to date.
[INFO] (yabormeparser) This package is up to date.
[INFO] (yabox) Data has been updated for this package.
[INFO] (yabt) This package is up to date.
[INFO] (yabtool) Data has been updated for this package.
[INFO] (yac) This package is up to date.
[ERROR] (yac-scrypt) Could not extract data from this package. See below for details.
"https://bitbucket.org/mmitech/yac_scrypt/get/12613d54f43a.zip" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yacbv) This package is up to date.
[INFO] (yacgol) This package is up to date.
[INFO] (yachain) This package is up to date.
[INFO] (yaci) Data has been updated for this package.
[ERROR] (yacis) This package does not have downloadable releases.
[INFO] (yack) This package is up to date.
[INFO] (yacl) Data has been updated for this package.
[INFO] (yacli) This package is up to date.
[INFO] (yaclifw) This package is up to date.
[INFO] (yacluster) This package is up to date.
[INFO] (yacm) This package is up to date.
[INFO] (yacman) Data has been updated for this package.
[INFO] (yacms) This package is up to date.
[INFO] (yacmt-core) This package is up to date.
[INFO] (yacmt-gui) This package is up to date.
[INFO] (yaco) This package is up to date.
[INFO] (yaco-applyfun) This package is up to date.
[INFO] (yaco-deliverancethemeselector) This package is up to date.
[INFO] (yaco-hghooks) This package is up to date.
[INFO] (yaco-recipe-cert) This package is up to date.
[INFO] (yaco-recipe-medialinker) This package is up to date.
[INFO] (yaco-recipe-patch) This package is up to date.
[INFO] (yaco-recipe-pycairo) This package is up to date.
[INFO] (yaco-recipe-uwsgi) This package is up to date.
[INFO] (yaco-releaser) This package is up to date.
[INFO] (yacof) Data has been updated for this package.
[INFO] (yaconf) This package is up to date.
[INFO] (yacontracts) This package is up to date.
[INFO] (yacron) Data has been updated for this package.
[INFO] (yacryptopan) This package is up to date.
[INFO] (yacs) This package is up to date.
[INFO] (yact) This package is up to date.
[INFO] (yad) This package is up to date.
[INFO] (yada) Data has been updated for this package.
[INFO] (yadage) Data has been updated for this package.
[INFO] (yadage-fork) This package is up to date.
[INFO] (yadage-haiku) This package is up to date.
[INFO] (yadage-httpctrl-server) This package is up to date.
[INFO] (yadage-schemas) This package is up to date.
[INFO] (yadage-service-cli) This package is up to date.
[INFO] (yadapy) This package is up to date.
[INFO] (yadashcomp) This package is up to date.
[INFO] (yadayada) This package is up to date.
[ERROR] (yadda) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yaddle) This package is up to date.
[INFO] (yadi) This package is up to date.
[INFO] (yadi-framework) This package is up to date.
[INFO] (yadi-py) This package is up to date.
[INFO] (yadi2) This package is up to date.
[INFO] (yadic) This package is up to date.
[INFO] (yadict-compare) This package is up to date.
[INFO] (yadil) This package is up to date.
[INFO] (yadisk) This package is up to date.
[INFO] (yadisk-api) This package is up to date.
[INFO] (yadisk-async) This package is up to date.
[INFO] (yadiskclient) This package is up to date.
[INFO] (yadl) This package is up to date.
[INFO] (yadll) This package is up to date.
[INFO] (yadlt) This package is up to date.
[INFO] (yadm) This package is up to date.
[INFO] (yadns) This package is up to date.
[INFO] (yadokari) This package is up to date.
[INFO] (yadoma) This package is up to date.
[INFO] (yadtbroadcast-client) This package is up to date.
[INFO] (yadtbroadcast-client-wamp2) This package is up to date.
[INFO] (yadtcommons) This package is up to date.
[INFO] (yadtcontroller) This package is up to date.
[INFO] (yadtreceiver) This package is up to date.
[INFO] (yadtshell) This package is up to date.
[INFO] (yadupe) Data has been updated for this package.
[INFO] (yaenum) This package is up to date.
[INFO] (yaenv) Data has been updated for this package.
[INFO] (yaep) This package is up to date.
[INFO] (yaf) Data has been updated for this package.
[INFO] (yafa-grpc) This package is up to date.
[INFO] (yafasttext) This package is up to date.
[INFO] (yafe) This package is up to date.
[INFO] (yaff) This package is up to date.
[INFO] (yafg) Data has been updated for this package.
[INFO] (yafowil) Data has been updated for this package.
[INFO] (yafowil-bootstrap) This package is up to date.
[INFO] (yafowil-documentation) This package is up to date.
[INFO] (yafowil-lingua) This package is up to date.
[INFO] (yafowil-plone) This package is up to date.
[INFO] (yafowil-webob) This package is up to date.
[INFO] (yafowil-werkzeug) This package is up to date.
[INFO] (yafowil-widget-ace) This package is up to date.
[INFO] (yafowil-widget-array) Data has been updated for this package.
[INFO] (yafowil-widget-autocomplete) This package is up to date.
[INFO] (yafowil-widget-chosen) This package is up to date.
[INFO] (yafowil-widget-cron) This package is up to date.
[INFO] (yafowil-widget-datetime) This package is up to date.
[INFO] (yafowil-widget-dict) This package is up to date.
[INFO] (yafowil-widget-dynatree) This package is up to date.
[INFO] (yafowil-widget-image) This package is up to date.
[INFO] (yafowil-widget-location) This package is up to date.
[INFO] (yafowil-widget-multiselect) This package is up to date.
[INFO] (yafowil-widget-recaptcha) This package is up to date.
[INFO] (yafowil-widget-richtext) This package is up to date.
[INFO] (yafowil-widget-select2) This package is up to date.
[INFO] (yafowil-widget-slider) This package is up to date.
[INFO] (yafowil-widget-wysihtml5) This package is up to date.
[INFO] (yafowil-yaml) This package is up to date.
[INFO] (yafowil-zope2) This package is up to date.
[INFO] (yafs) This package is up to date.
[INFO] (yafsm) This package is up to date.
[INFO] (yaft) This package is up to date.
[INFO] (yafte) This package is up to date.
[INFO] (yag) This package is up to date.
[INFO] (yagdspy) This package is up to date.
[INFO] (yaghurl) This package is up to date.
[INFO] (yagi) This package is up to date.
[INFO] (yagmail) Data has been updated for this package.
[INFO] (yagmail-foxmail) This package is up to date.
[INFO] (yagmail-outlook) This package is up to date.
[INFO] (yagocd) This package is up to date.
[INFO] (yagolabelfetcherpy) This package is up to date.
[INFO] (yagt) This package is up to date.
[INFO] (yagura) This package is up to date.
[INFO] (yaha) This package is up to date.
[INFO] (yahi) This package is up to date.
[ERROR] (yahiko) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "http://samurai-x.org/downloads/"
[INFO] (yahmm) This package is up to date.
[INFO] (yahoo) This package is up to date.
[INFO] (yahoo-api) This package is up to date.
[ERROR] (yahoo-contrib-panoptes) This package does not have downloadable releases.
[INFO] (yahoo-earnings-calendar) This package is up to date.
[INFO] (yahoo-fantasy-api) Data has been updated for this package.
[INFO] (yahoo-ff) This package is up to date.
[INFO] (yahoo-fin) Data has been updated for this package.
[INFO] (yahoo-finance) This package is up to date.
[INFO] (yahoo-finance-api2) This package is up to date.
[INFO] (yahoo-finance-hdd) Data has been updated for this package.
[INFO] (yahoo-finance-pandas) This package is up to date.
[INFO] (yahoo-finance-pynterface) This package is up to date.
[INFO] (yahoo-finance-stock-ticker) This package is up to date.
[INFO] (yahoo-historical) Data has been updated for this package.
[INFO] (yahoo-market-data) This package is up to date.
[INFO] (yahoo-oauth) This package is up to date.
[INFO] (yahoo-panoptes) Data has been updated for this package.
[INFO] (yahoo-panoptes-snmp) Data has been updated for this package.
[INFO] (yahoo-quote-download) Data has been updated for this package.
[INFO] (yahoo-ticker-downloader) This package is up to date.
[INFO] (yahoo-weather) This package is up to date.
[INFO] (yahooauction-bidder) This package is up to date.
[INFO] (yahoofantasy) This package is up to date.
[INFO] (yahoofantasyfootball) This package is up to date.
[INFO] (yahoofinance) This package is up to date.
[INFO] (yahoofinancedashboard) Data has been updated for this package.
[INFO] (yahoofinancedataloader) Data has been updated for this package.
[INFO] (yahoofinancespider) This package is up to date.
[INFO] (yahoofinancials) This package is up to date.
[INFO] (yahoojapandatareader) This package is up to date.
[INFO] (yahooooo) Data has been updated for this package.
[INFO] (yahooquery) Data has been updated for this package.
[INFO] (yahooscraper) This package is up to date.
[INFO] (yahooweather) This package is up to date.
[INFO] (yahs) This package is up to date.
[INFO] (yai) This package is up to date.
[INFO] (yail) This package is up to date.
[INFO] (yaipopt) This package is up to date.
[INFO] (yais) Data has been updated for this package.
[INFO] (yajl) This package is up to date.
[INFO] (yajl-py) This package is up to date.
[INFO] (yajs) This package is up to date.
[INFO] (yak) This package is up to date.
[ERROR] (yak-nester) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yak-signals) This package is up to date.
[INFO] (yak-yurt) This package is up to date.
[INFO] (yakc) This package is up to date.
[INFO] (yake) This package is up to date.
[INFO] (yake-github) This package is up to date.
[INFO] (yakindlestrip) This package is up to date.
[INFO] (yakonfig) This package is up to date.
[INFO] (yaks) Data has been updated for this package.
[INFO] (yaksh) This package is up to date.
[INFO] (yakstack) This package is up to date.
[INFO] (yakt) This package is up to date.
[INFO] (yakumo) This package is up to date.
[INFO] (yakusoku) This package is up to date.
[INFO] (yakutils) Data has been updated for this package.
[INFO] (yala) Data has been updated for this package.
[INFO] (yalchemy) Data has been updated for this package.
[INFO] (yale-dhlab-facenet) Data has been updated for this package.
[INFO] (yale-dhlab-keras-preprocessing) Data has been updated for this package.
[INFO] (yale-dhlab-rasterfairy) This package is up to date.
[INFO] (yalebuildings) This package is up to date.
[INFO] (yalecourses) This package is up to date.
[INFO] (yaledining) Data has been updated for this package.
[INFO] (yaledirectory) This package is up to date.
[INFO] (yalelaundry) Data has been updated for this package.
[INFO] (yaleorgdirectory) This package is up to date.
[INFO] (yalesmartalarmclient) This package is up to date.
[INFO] (yalesnotes) This package is up to date.
[INFO] (yali-server) This package is up to date.
[INFO] (yalign) This package is up to date.
[INFO] (yall) This package is up to date.
[INFO] (yalla) This package is up to date.
[INFO] (yalogger) Data has been updated for this package.
[INFO] (yalp) This package is up to date.
[INFO] (yalp-grok) This package is up to date.
[INFO] (yalpt) This package is up to date.
[INFO] (yalr) This package is up to date.
[INFO] (yam) This package is up to date.
[INFO] (yam-sort) Data has been updated for this package.
[INFO] (yama) This package is up to date.
[INFO] (yamaha-av) Data has been updated for this package.
[INFO] (yamail) Data has been updated for this package.
[ERROR] (yamake) This package does not have downloadable releases.
[INFO] (yamale) Data has been updated for this package.
[INFO] (yamanifest) This package is up to date.
[INFO] (yamas) Data has been updated for this package.
[INFO] (yamata) This package is up to date.
[INFO] (yamb) This package is up to date.
[INFO] (yamconv) Data has been updated for this package.
[INFO] (yamcs-cli) Data has been updated for this package.
[INFO] (yamcs-client) Data has been updated for this package.
[INFO] (yamdl) This package is up to date.
[INFO] (yametrikapy) This package is up to date.
[INFO] (yamf) This package is up to date.
[INFO] (yamgl-gen) This package is up to date.
[INFO] (yamicache) This package is up to date.
[INFO] (yamily) Data has been updated for this package.
[INFO] (yamjam) This package is up to date.
[INFO] (yamkix) Data has been updated for this package.
[ERROR] (yaml) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (yaml-1-2) This package does not have downloadable releases.
[INFO] (yaml-1-3) This package is up to date.
[INFO] (yaml-backed-structs) This package is up to date.
[INFO] (yaml-builder) This package is up to date.
[INFO] (yaml-config) This package is up to date.
[INFO] (yaml-config-parser) This package is up to date.
[INFO] (yaml-configuration) This package is up to date.
[INFO] (yaml-dump) This package is up to date.
[INFO] (yaml-injection) Data has been updated for this package.
[INFO] (yaml-mako) This package is up to date.
[INFO] (yaml-merge) This package is up to date.
[INFO] (yaml-model) This package is up to date.
[INFO] (yaml-project-loader) This package is up to date.
[INFO] (yaml-resume) Data has been updated for this package.
[INFO] (yaml-rulz) This package is up to date.
[INFO] (yaml-tags) This package is up to date.
[INFO] (yaml-to-object) This package is up to date.
[INFO] (yaml-to-sqlite) Data has been updated for this package.
[INFO] (yaml-utilities) This package is up to date.
[INFO] (yaml2bib) Data has been updated for this package.
[INFO] (yaml2cli) This package is up to date.
[INFO] (yaml2dot) Data has been updated for this package.
[INFO] (yaml2ical) This package is up to date.
[INFO] (yaml2object) This package is up to date.
[INFO] (yaml2pac) This package is up to date.
[INFO] (yaml2rst) This package is up to date.
[INFO] (yaml2syntax) Data has been updated for this package.
[INFO] (yaml2tree) Data has been updated for this package.
[INFO] (yaml2treeview) Data has been updated for this package.
[INFO] (yaml2txt) Data has been updated for this package.
[INFO] (yaml4rst) This package is up to date.
[INFO] (yamlable) Data has been updated for this package.
[INFO] (yamlapi) Data has been updated for this package.
[INFO] (yamlargparse) Data has been updated for this package.
[INFO] (yamlbro) This package is up to date.
[INFO] (yamlcf) This package is up to date.
[INFO] (yamlcfg) This package is up to date.
[INFO] (yamlchecker) This package is up to date.
[INFO] (yamlcli) Data has been updated for this package.
[INFO] (yamlcompute) Data has been updated for this package.
[INFO] (yamlconf) This package is up to date.
[INFO] (yamlconfig) This package is up to date.
[INFO] (yamldata) This package is up to date.
[INFO] (yamldata2asn1) Data has been updated for this package.
[INFO] (yamldata2json) Data has been updated for this package.
[INFO] (yamldata2xml) Data has been updated for this package.
[INFO] (yamldataclassconfig) Data has been updated for this package.
[INFO] (yamldatadiff) Data has been updated for this package.
[INFO] (yamldatafind) Data has been updated for this package.
[INFO] (yamldataunit) Data has been updated for this package.
[INFO] (yamldict) Data has been updated for this package.
[INFO] (yamldirs) Data has been updated for this package.
[INFO] (yamldown) This package is up to date.
[INFO] (yamlenc) This package is up to date.
[INFO] (yamlenv) This package is up to date.
[INFO] (yamlfmt) Data has been updated for this package.
[INFO] (yamlfred) This package is up to date.
[INFO] (yamli) This package is up to date.
[INFO] (yamlicious) This package is up to date.
[INFO] (yamlifier) This package is up to date.
[INFO] (yamline) This package is up to date.
[INFO] (yamlinfo) This package is up to date.
[INFO] (yamlious) This package is up to date.
[INFO] (yamlish) This package is up to date.
[INFO] (yamlisp) This package is up to date.
[ERROR] (yamlite) This package does not have downloadable releases.
[INFO] (yamliz) Data has been updated for this package.
[INFO] (yamlize) This package is up to date.
[INFO] (yamllathe) Data has been updated for this package.
[INFO] (yamllint) Data has been updated for this package.
[INFO] (yamllint-junit) This package is up to date.
[INFO] (yamllintbear) This package is up to date.
[INFO] (yamllintelerir) Data has been updated for this package.
[ERROR] (yamllintelerirelerir) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (yamllintmod) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yamlloader) This package is up to date.
[INFO] (yamlmagic) This package is up to date.
[INFO] (yamlmod) This package is up to date.
[INFO] (yamlns) Data has been updated for this package.
[INFO] (yamlodm) This package is up to date.
[INFO] (yamlog) This package is up to date.
[ERROR] (yamlog-0-9) This package does not have downloadable releases.
[INFO] (yamlord) This package is up to date.
[INFO] (yamlordereddictloader) This package is up to date.
[INFO] (yamlpage) This package is up to date.
[INFO] (yamlpal) This package is up to date.
[INFO] (yamlparse) Data has been updated for this package.
[INFO] (yamlpath) Data has been updated for this package.
[INFO] (yamlplus) Data has been updated for this package.
[INFO] (yamlradio) This package is up to date.
[INFO] (yamlreader) This package is up to date.
[INFO] (yamlschema) This package is up to date.
[INFO] (yamlsettings) This package is up to date.
[INFO] (yamlsettings-requests) This package is up to date.
[INFO] (yamlsettings-s3) This package is up to date.
[INFO] (yamlspellchecker) This package is up to date.
[INFO] (yamlstratus) This package is up to date.
[INFO] (yamltable) Data has been updated for this package.
[INFO] (yamltojsoncreator) Data has been updated for this package.
[INFO] (yamltools) This package is up to date.
[INFO] (yamltrak) This package is up to date.
[INFO] (yamltypes) This package is up to date.
[INFO] (yamly) This package is up to date.
[INFO] (yamm) Data has been updated for this package.
[INFO] (yammh3) This package is up to date.
[INFO] (yammtool) This package is up to date.
[INFO] (yammy) This package is up to date.
[INFO] (yamo) This package is up to date.
[INFO] (yamodel) This package is up to date.
[INFO] (yamole) This package is up to date.
[INFO] (yamp) This package is up to date.
[INFO] (yampex) Data has been updated for this package.
[INFO] (yampy) This package is up to date.
[INFO] (yampy2) Data has been updated for this package.
[INFO] (yams) Data has been updated for this package.
[INFO] (yamscrobbler) This package is up to date.
[INFO] (yamux) Data has been updated for this package.
[INFO] (yamwapi) This package is up to date.
[INFO] (yamz) Data has been updated for this package.
[INFO] (yanagiba) This package is up to date.
[INFO] (yanc) This package is up to date.
[INFO] (yanch2116) This package is up to date.
[INFO] (yanchaotest) This package is up to date.
[INFO] (yandc) This package is up to date.
[INFO] (yandex) Data has been updated for this package.
[INFO] (yandex-checkout) Data has been updated for this package.
[INFO] (yandex-ci-parser) This package is up to date.
[INFO] (yandex-connect) Data has been updated for this package.
[INFO] (yandex-delivery) This package is up to date.
[ERROR] (yandex-domain-mail) This package does not have downloadable releases.
[INFO] (yandex-geocoder) Data has been updated for this package.
[INFO] (yandex-hotspots) This package is up to date.
[INFO] (yandex-images-download) Data has been updated for this package.
[INFO] (yandex-kassa) This package is up to date.
[INFO] (yandex-maps) This package is up to date.
[INFO] (yandex-money-sdk) This package is up to date.
[INFO] (yandex-music) Data has been updated for this package.
[INFO] (yandex-oauth-py) This package is up to date.
[INFO] (yandex-parser) Data has been updated for this package.
[INFO] (yandex-pdd) This package is up to date.
[INFO] (yandex-pgmigrate) This package is up to date.
[INFO] (yandex-rasp) This package is up to date.
[INFO] (yandex-search) This package is up to date.
[INFO] (yandex-speech) This package is up to date.
[INFO] (yandex-tank-api) This package is up to date.
[INFO] (yandex-tank-api-client) This package is up to date.
[INFO] (yandex-tracker-client) Data has been updated for this package.
[INFO] (yandex-translate) This package is up to date.
[INFO] (yandex-translater) This package is up to date.
[INFO] (yandex-translater-api) This package is up to date.
[INFO] (yandex-transport-webdriver-api) This package is up to date.
[INFO] (yandex-weather-api) This package is up to date.
[INFO] (yandex-xml-parser) This package is up to date.
[INFO] (yandex-yaca-parser) This package is up to date.
[INFO] (yandexcloud) Data has been updated for this package.
[INFO] (yandexdictionary) This package is up to date.
[INFO] (yandexdirect) This package is up to date.
[INFO] (yandexmaps) This package is up to date.
[INFO] (yandextank) This package is up to date.
[ERROR] (yandextransportwebdriverapi) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yandexwebdav) This package is up to date.
[INFO] (yandexwebmaster) This package is up to date.
[INFO] (yang) This package is up to date.
[INFO] (yang-connector) Data has been updated for this package.
[INFO] (yang-ncdiff) This package is up to date.
[INFO] (yang-print-list) This package is up to date.
[INFO] (yang0textutils) This package is up to date.
[INFO] (yang2tosca) This package is up to date.
[INFO] (yangdi-loveyou-loveyou) This package is up to date.
[INFO] (yangify) Data has been updated for this package.
[INFO] (yangsgoogle) This package is up to date.
[ERROR] (yangshanghua) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yangson) Data has been updated for this package.
[INFO] (yangsrunner) This package is up to date.
[INFO] (yangsutil) This package is up to date.
[INFO] (yangsz716) This package is up to date.
[INFO] (yangtestlist) This package is up to date.
[INFO] (yangverification) This package is up to date.
[INFO] (yangyangyang123) This package is up to date.
[INFO] (yangyaya) This package is up to date.
[INFO] (yangyijin) Data has been updated for this package.
[ERROR] (yanico) This package does not have downloadable releases.
[INFO] (yanker) This package is up to date.
[INFO] (yanktv) This package is up to date.
[INFO] (yanky) This package is up to date.
[INFO] (yanlp) This package is up to date.
[INFO] (yann) Data has been updated for this package.
[INFO] (yanncookiecutter) Data has been updated for this package.
[INFO] (yanotme-nester) This package is up to date.
[INFO] (yanpj) This package is up to date.
[INFO] (yanport-client) This package is up to date.
[INFO] (yans) This package is up to date.
[INFO] (yans-nester) This package is up to date.
[INFO] (yansongda-aliyun-iot-device) Data has been updated for this package.
[INFO] (yantra) This package is up to date.
[ERROR] (yanventory) This package does not have downloadable releases.
[INFO] (yanwang-sample) This package is up to date.
[INFO] (yanytapi) This package is up to date.
[INFO] (yanyujian) This package is up to date.
[INFO] (yao-framework) Data has been updated for this package.
[INFO] (yaochao) This package is up to date.
[INFO] (yaoguang-python-client) This package is up to date.
[INFO] (yaojiawei20161104) This package is up to date.
[INFO] (yaop) This package is up to date.
[INFO] (yaosac) This package is up to date.
[INFO] (yaoshazi) This package is up to date.
[INFO] (yaosint) Data has been updated for this package.
[INFO] (yaost) Data has been updated for this package.
[INFO] (yaoyao-athletelist-20180112) This package is up to date.
[INFO] (yaoyao-nest-20171212) This package is up to date.
[INFO] (yap) This package is up to date.
[INFO] (yapatch) This package is up to date.
[INFO] (yapayzeka) This package is up to date.
[INFO] (yapayzekadj) This package is up to date.
[INFO] (yapbl) This package is up to date.
[INFO] (yapbol) Data has been updated for this package.
[INFO] (yapconf) Data has been updated for this package.
[INFO] (yapdfminer) Data has been updated for this package.
[INFO] (yapdict) This package is up to date.
[INFO] (yapf) Data has been updated for this package.
[INFO] (yapf-junit) This package is up to date.
[INFO] (yapfbear) This package is up to date.
[INFO] (yapfsm) This package is up to date.
[INFO] (yapg) Data has been updated for this package.
[ERROR] (yapgvb) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "http://code.google.com/p/yapgvb/downloads/list?can=1&q=&colspec=Filename+Summary+Uploaded+Size+DownloadCount"
[INFO] (yaphs) This package is up to date.
[INFO] (yaphue) This package is up to date.
[INFO] (yapi) This package is up to date.
[INFO] (yapi-ci) Data has been updated for this package.
[INFO] (yapic) This package is up to date.
[INFO] (yapic-di) This package is up to date.
[INFO] (yapic-io) This package is up to date.
[INFO] (yapic-json) Data has been updated for this package.
[INFO] (yapij-py) This package is up to date.
[INFO] (yaplon) Data has been updated for this package.
[INFO] (yaplotlib) This package is up to date.
[INFO] (yapo) Data has been updated for this package.
[INFO] (yapocis) This package is up to date.
[INFO] (yaposib) This package is up to date.
[INFO] (yapot) This package is up to date.
[ERROR] (yapp) This package does not have downloadable releases.
[INFO] (yappa) Data has been updated for this package.
[INFO] (yappi) Data has been updated for this package.
[INFO] (yapps) This package is up to date.
[INFO] (yapps2) This package is up to date.
[INFO] (yappt) This package is up to date.
[INFO] (yappyg) This package is up to date.
[INFO] (yapq) Data has been updated for this package.
[INFO] (yaprt) This package is up to date.
[INFO] (yaps) This package is up to date.
[ERROR] (yapsnmp) Could not extract data from this package. See below for details.
".php" extension not supported.
[INFO] (yapsstv) This package is up to date.
[INFO] (yapsy) Data has been updated for this package.
[INFO] (yapt) This package is up to date.
[ERROR] (yaptoo) Could not extract data from this package. See below for details.
".py" extension not supported.
[INFO] (yapyaci) Data has been updated for this package.
[INFO] (yapyautotest) This package is up to date.
[INFO] (yapybot) This package is up to date.
[INFO] (yapydata) Data has been updated for this package.
[INFO] (yapylib) This package is up to date.
[INFO] (yapyorg) This package is up to date.
[INFO] (yapyseq) This package is up to date.
[INFO] (yapytf) This package is up to date.
[INFO] (yapyutils) Data has been updated for this package.
[INFO] (yapyvcloud) This package is up to date.
[INFO] (yapywrangler) This package is up to date.
[INFO] (yaq) This package is up to date.
[INFO] (yaqc) Data has been updated for this package.
[INFO] (yaqd-control) Data has been updated for this package.
[INFO] (yaqd-core) Data has been updated for this package.
[INFO] (yaqd-gdrive) Data has been updated for this package.
[INFO] (yaqd-horiba) Data has been updated for this package.
[INFO] (yaql) This package is up to date.
[INFO] (yaque-tts) This package is up to date.
[INFO] (yara) This package is up to date.
[INFO] (yara-procdump-python) This package is up to date.
[INFO] (yara-python) Data has been updated for this package.
[INFO] (yara-scanner) Data has been updated for this package.
[INFO] (yaramod) Data has been updated for this package.
[INFO] (yaraprocessor) This package is up to date.
[INFO] (yaratool) This package is up to date.
[INFO] (yarb) This package is up to date.
[INFO] (yarbs) This package is up to date.
[INFO] (yarc) Data has been updated for this package.
[INFO] (yard) This package is up to date.
[INFO] (yard-framework) This package is up to date.
[INFO] (yardict) This package is up to date.
[ERROR] (yardstick) This package does not have downloadable releases.
[INFO] (yarely) This package is up to date.
[INFO] (yarest) This package is up to date.
[INFO] (yaretry) This package is up to date.
[ERROR] (yarfe) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yarfox) This package is up to date.
[INFO] (yarg) This package is up to date.
[INFO] (yargs) This package is up to date.
[INFO] (yargy) This package is up to date.
[ERROR] (yarh) This package does not have downloadable releases.
[INFO] (yarl) Data has been updated for this package.
[INFO] (yarll) Data has been updated for this package.
[INFO] (yarlp) This package is up to date.
[INFO] (yarma) This package is up to date.
[INFO] (yarn-api-client) Data has been updated for this package.
[INFO] (yarn-api-client-kenny) This package is up to date.
[INFO] (yarn-build) This package is up to date.
[INFO] (yarn-kernel-provider) Data has been updated for this package.
[INFO] (yarn-unreg-nodes) This package is up to date.
[INFO] (yarnapiclient) This package is up to date.
[INFO] (yarntf) This package is up to date.
[INFO] (yaro) This package is up to date.
[INFO] (yarom) Data has been updated for this package.
[INFO] (yarp) This package is up to date.
[INFO] (yarpc) This package is up to date.
[INFO] (yarptp) This package is up to date.
[INFO] (yarqueue) Data has been updated for this package.
[INFO] (yarr-client) This package is up to date.
[ERROR] (yarrow) Could not extract data from this package. See below for details.
"ftp://ftp.thurman.org.uk/pub/thurman/rgtp/yarrow-1.2.0.tar.gz" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/lib/python3.7/urllib/request.py", line 1525, in ftp_open
    host = socket.gethostbyname(host)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1527, in ftp_open
    raise URLError(msg)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

[INFO] (yars) This package is up to date.
[INFO] (yarw) This package is up to date.
[INFO] (yas) Data has been updated for this package.
[INFO] (yas3fs) This package is up to date.
[INFO] (yasa) Data has been updated for this package.
[INFO] (yasal) This package is up to date.
[INFO] (yascp) This package is up to date.
[INFO] (yascrape) This package is up to date.
[INFO] (yasd) This package is up to date.
[INFO] (yased) This package is up to date.
[INFO] (yasexamplehandlers) This package is up to date.
[INFO] (yasfb) This package is up to date.
[INFO] (yasgg) This package is up to date.
[INFO] (yash) This package is up to date.
[INFO] (yasha) This package is up to date.
[INFO] (yashiro) Data has been updated for this package.
[INFO] (yasi) This package is up to date.
[INFO] (yasjenkins) Data has been updated for this package.
[INFO] (yask123) This package is up to date.
[INFO] (yasl) This package is up to date.
[INFO] (yaslackmessenger) Data has been updated for this package.
[INFO] (yaslha) This package is up to date.
[INFO] (yaslov) This package is up to date.
[INFO] (yasm) This package is up to date.
[INFO] (yasmin) This package is up to date.
[INFO] (yason) This package is up to date.
[INFO] (yasoo) Data has been updated for this package.
[INFO] (yasopenstackhandler) This package is up to date.
[INFO] (yaspin) Data has been updated for this package.
[INFO] (yass) This package is up to date.
[INFO] (yass-algorithm) This package is up to date.
[INFO] (yassh) This package is up to date.
[INFO] (yasso) This package is up to date.
[INFO] (yast) This package is up to date.
[INFO] (yastatsd) This package is up to date.
[INFO] (yasuf) This package is up to date.
[INFO] (yasv) This package is up to date.
[INFO] (yaswfp) This package is up to date.
[INFO] (yata) This package is up to date.
[INFO] (yatadis) This package is up to date.
[INFO] (yatank-online) This package is up to date.
[INFO] (yatcobot) This package is up to date.
[INFO] (yate) This package is up to date.
[INFO] (yate-lhwd) This package is up to date.
[INFO] (yated) This package is up to date.
[INFO] (yatel) This package is up to date.
[INFO] (yatfs) This package is up to date.
[INFO] (yatfsrpc) This package is up to date.
[INFO] (yatg) Data has been updated for this package.
[INFO] (yati) This package is up to date.
[INFO] (yatiblog) This package is up to date.
[INFO] (yatiml) This package is up to date.
[INFO] (yatl) Data has been updated for this package.
[INFO] (yatodol) This package is up to date.
[INFO] (yatom) This package is up to date.
[INFO] (yatoredis) This package is up to date.
[INFO] (yatr) This package is up to date.
[INFO] (yatracker) Data has been updated for this package.
[INFO] (yatrash) This package is up to date.
[INFO] (yatrep) Data has been updated for this package.
[INFO] (yattag) Data has been updated for this package.
[INFO] (yatwin) This package is up to date.
[INFO] (yatxmilter) This package is up to date.
[ERROR] (yaubot) Could not extract data from this package. See below for details.
"http://www.jakebasile.com/downloads/yaubot-1.0.tar.gz" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (yaubot-fun-scripts) Could not extract data from this package. See below for details.
"http://www.jakebasile.com/downloads/yaubot-fun-scripts-1.0.tar.gz" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yaul) This package is up to date.
[INFO] (yaurtww) This package is up to date.
[INFO] (yauth) This package is up to date.
[INFO] (yaval) This package is up to date.
[INFO] (yawap) Data has been updated for this package.
[INFO] (yawast) Data has been updated for this package.
[INFO] (yawd-admin) This package is up to date.
[INFO] (yawd-elfinder) This package is up to date.
[INFO] (yawd-translations) This package is up to date.
[INFO] (yawf) This package is up to date.
[INFO] (yawigle) Data has been updated for this package.
[INFO] (yawinpty) This package is up to date.
[INFO] (yawinpty-extra) This package is up to date.
[INFO] (yawlib) This package is up to date.
[INFO] (yawn) This package is up to date.
[INFO] (yawns) Data has been updated for this package.
[ERROR] (yawpycrypto) This package does not have downloadable releases.
[INFO] (yawrap) Data has been updated for this package.
[INFO] (yaws) This package is up to date.
[INFO] (yawttk) This package is up to date.
[INFO] (yawxt) This package is up to date.
[INFO] (yax) This package is up to date.
[INFO] (yaxil) Data has been updated for this package.
[INFO] (yaxl) This package is up to date.
[INFO] (yaxls) This package is up to date.
[ERROR] (yaxmake) This package does not have downloadable releases.
[INFO] (yay) This package is up to date.
[ERROR] (yaya) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (yayayayahw) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yaybu) This package is up to date.
[INFO] (yaycl) This package is up to date.
[INFO] (yaycl-crypt) This package is up to date.
[INFO] (yayconf) Data has been updated for this package.
[INFO] (yayes) Data has been updated for this package.
[INFO] (yayi) This package is up to date.
[ERROR] (yayp) This package does not have downloadable releases.
[INFO] (yaypm) This package is up to date.
[INFO] (yayson) This package is up to date.
[INFO] (yaz) This package is up to date.
[INFO] (yaz-messaging-plugin) This package is up to date.
[INFO] (yaz-scripting-plugin) This package is up to date.
[INFO] (yaz-templating-plugin) This package is up to date.
[INFO] (yaz-zichtgithub-plugin) Data has been updated for this package.
[INFO] (yaz0) This package is up to date.
[INFO] (yazaki) Data has been updated for this package.
[INFO] (yb-cassandra-driver) This package is up to date.
[INFO] (ybai) This package is up to date.
[INFO] (ybc-agent) This package is up to date.
[INFO] (ybc-animal) This package is up to date.
[INFO] (ybc-art) This package is up to date.
[INFO] (ybc-bot) This package is up to date.
[INFO] (ybc-box) This package is up to date.
[INFO] (ybc-browser) This package is up to date.
[INFO] (ybc-business-ocr) This package is up to date.
[INFO] (ybc-calculate) This package is up to date.
[INFO] (ybc-camera) This package is up to date.
[INFO] (ybc-car-recognition) This package is up to date.
[INFO] (ybc-carbrand) This package is up to date.
[INFO] (ybc-china) This package is up to date.
[INFO] (ybc-config) This package is up to date.
[INFO] (ybc-coordinate) This package is up to date.
[INFO] (ybc-cpaint) This package is up to date.
[INFO] (ybc-creditcard-ocr) This package is up to date.
[INFO] (ybc-descpic) This package is up to date.
[INFO] (ybc-download) This package is up to date.
[INFO] (ybc-driver-ocr) This package is up to date.
[INFO] (ybc-echarts) This package is up to date.
[INFO] (ybc-emoji) This package is up to date.
[INFO] (ybc-exception) This package is up to date.
[INFO] (ybc-face) This package is up to date.
[INFO] (ybc-face-emotion) This package is up to date.
[INFO] (ybc-face-ps) This package is up to date.
[INFO] (ybc-face-recognition) This package is up to date.
[INFO] (ybc-food) This package is up to date.
[INFO] (ybc-funny) This package is up to date.
[INFO] (ybc-general-ocr) This package is up to date.
[INFO] (ybc-gesture) This package is up to date.
[INFO] (ybc-history) This package is up to date.
[INFO] (ybc-idcard) This package is up to date.
[INFO] (ybc-idcard-ocr) This package is up to date.
[INFO] (ybc-idiom) This package is up to date.
[INFO] (ybc-image) This package is up to date.
[INFO] (ybc-imgaddtext) This package is up to date.
[INFO] (ybc-imgcar) This package is up to date.
[INFO] (ybc-imgtag) This package is up to date.
[INFO] (ybc-jiqimao) This package is up to date.
[INFO] (ybc-music) This package is up to date.
[INFO] (ybc-namecard) This package is up to date.
[ERROR] (ybc-namecard-ocr) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (ybc-news) This package is up to date.
[INFO] (ybc-pic-search) This package is up to date.
[INFO] (ybc-pinyin) This package is up to date.
[INFO] (ybc-player) This package is up to date.
[INFO] (ybc-pminfo) This package is up to date.
[INFO] (ybc-poetry) This package is up to date.
[INFO] (ybc-qrcode) This package is up to date.
[INFO] (ybc-rmb) This package is up to date.
[INFO] (ybc-scene) This package is up to date.
[INFO] (ybc-search) This package is up to date.
[INFO] (ybc-speech) This package is up to date.
[INFO] (ybc-speech1) This package is up to date.
[INFO] (ybc-switch) This package is up to date.
[INFO] (ybc-table) This package is up to date.
[INFO] (ybc-tel) This package is up to date.
[INFO] (ybc-test) This package is up to date.
[INFO] (ybc-todo) This package is up to date.
[INFO] (ybc-trans) This package is up to date.
[INFO] (ybc-tuya) This package is up to date.
[INFO] (ybc-utils) This package is up to date.
[INFO] (ybc-weather) This package is up to date.
[INFO] (ybc-wordcloud) This package is up to date.
[INFO] (ybc-xingzuo) This package is up to date.
[INFO] (ybc-xzpq) This package is up to date.
[INFO] (ybc-youtuyun) This package is up to date.
[INFO] (ybckit) This package is up to date.
[INFO] (ybemail) This package is up to date.
[ERROR] (ybklist) This package does not have downloadable releases.
[INFO] (yboss) This package is up to date.
[INFO] (ybt) Data has been updated for this package.
[INFO] (ybw) This package is up to date.
[INFO] (ycast) Data has been updated for this package.
[INFO] (yccloudpickle) This package is up to date.
[INFO] (ycfg) This package is up to date.
[INFO] (ychartspy) This package is up to date.
[INFO] (ychat) Data has been updated for this package.
[INFO] (ycimpute) This package is up to date.
[INFO] (ycl) This package is up to date.
[INFO] (yclip) This package is up to date.
[INFO] (ycm) This package is up to date.
[INFO] (ycml) This package is up to date.
[INFO] (yconf) This package is up to date.
[INFO] (yconfig) This package is up to date.
[INFO] (yconpy) This package is up to date.
[INFO] (ycp-nester) This package is up to date.
[INFO] (ycsettings) This package is up to date.
[INFO] (ycy) This package is up to date.
[INFO] (ycyc) This package is up to date.
[INFO] (ycytest) This package is up to date.
[INFO] (yd) This package is up to date.
[INFO] (yd3) This package is up to date.
[INFO] (ydb) This package is up to date.
[INFO] (ydbf) This package is up to date.
[INFO] (ydbf-py3) This package is up to date.
[INFO] (ydcommon) This package is up to date.
[INFO] (ydcv) This package is up to date.
[INFO] (ydd) This package is up to date.
[INFO] (ydh-yourname) This package is up to date.
[INFO] (ydiff) This package is up to date.
[INFO] (ydk) Data has been updated for this package.
[INFO] (ydk-models-cisco-ios-xe) Data has been updated for this package.
[INFO] (ydk-models-cisco-ios-xr) Data has been updated for this package.
[INFO] (ydk-models-cisco-nx-os) Data has been updated for this package.
[INFO] (ydk-models-ietf) This package is up to date.
[INFO] (ydk-models-openconfig) This package is up to date.
[INFO] (ydk-service-gnmi) Data has been updated for this package.
[INFO] (ydl-binaries) This package is up to date.
[INFO] (ydoc-theme) This package is up to date.
[INFO] (ydown) This package is up to date.
[INFO] (ydsdk) Data has been updated for this package.
[INFO] (ydt) Data has been updated for this package.
[INFO] (ydtest) This package is up to date.
[INFO] (ydu) This package is up to date.
[INFO] (ydy-pkg) This package is up to date.
[INFO] (yeadon) This package is up to date.
[INFO] (yeager) This package is up to date.
[INFO] (yeahyeah) Data has been updated for this package.
[INFO] (yeahyfutils) This package is up to date.
[INFO] (yealinkmanager) Data has been updated for this package.
[INFO] (yeardays) This package is up to date.
[INFO] (yearfrac) Data has been updated for this package.
[INFO] (yearonedb) This package is up to date.
[INFO] (yearonequant) This package is up to date.
[ERROR] (yeast) This package does not have downloadable releases.
[INFO] (yedis) This package is up to date.
[INFO] (yeecli) This package is up to date.
[INFO] (yeeee) Data has been updated for this package.
[INFO] (yeekit-tr-free) Data has been updated for this package.
[INFO] (yeelib) This package is up to date.
[INFO] (yeelight) This package is up to date.
[INFO] (yeelight-cinema) This package is up to date.
[INFO] (yeelightsunflower) This package is up to date.
[INFO] (yeet) This package is up to date.
[INFO] (yeet-dl) This package is up to date.
[INFO] (yeeter) This package is up to date.
[INFO] (yehen-get-coach-data) This package is up to date.
[INFO] (yehen-nester) This package is up to date.
[INFO] (yehua) Data has been updated for this package.
[INFO] (yejidepdf) Data has been updated for this package.
[INFO] (yekit) This package is up to date.
[INFO] (yell) This package is up to date.
[INFO] (yelljfish) This package is up to date.
[INFO] (yellow-idea-py) Data has been updated for this package.
[INFO] (yellow-sdk) This package is up to date.
[INFO] (yellowant) This package is up to date.
[INFO] (yellowbrick) Data has been updated for this package.
[INFO] (yellowbrick-datasets) This package is up to date.
[INFO] (yellowfin) This package is up to date.
[INFO] (yellowhiggs) This package is up to date.
[INFO] (yellowpushsms) This package is up to date.
[INFO] (yelluw-matches) This package is up to date.
[INFO] (yelp) This package is up to date.
[INFO] (yelp-api-client) This package is up to date.
[INFO] (yelp-avro) This package is up to date.
[INFO] (yelp-bytes) This package is up to date.
[INFO] (yelp-cheetah) This package is up to date.
[INFO] (yelp-clog) This package is up to date.
[INFO] (yelp-encodings) This package is up to date.
[INFO] (yelp-gprof2dot) This package is up to date.
[INFO] (yelp-kafka) This package is up to date.
[INFO] (yelp-meteorite) This package is up to date.
[INFO] (yelp-uri) This package is up to date.
[INFO] (yelp3) This package is up to date.
[INFO] (yelpapi) This package is up to date.
[INFO] (yelpscraper) This package is up to date.
[INFO] (yelpy) This package is up to date.
[INFO] (yenc) This package is up to date.
[INFO] (yenviron) This package is up to date.
[INFO] (yenyupeng-nester) This package is up to date.
[INFO] (yeoda) Data has been updated for this package.
[INFO] (yeonji) Data has been updated for this package.
[INFO] (yep) This package is up to date.
[INFO] (yerkes) This package is up to date.
[INFO] (yes) This package is up to date.
[INFO] (yes24) This package is up to date.
[INFO] (yesaide) This package is up to date.
[INFO] (yescrypt-koto) This package is up to date.
[INFO] (yesgraph) This package is up to date.
[INFO] (yesno) This package is up to date.
[INFO] (yesqa) This package is up to date.
[INFO] (yessssms) Data has been updated for this package.
[INFO] (yesterday) Data has been updated for this package.
[INFO] (yeswecansvg) This package is up to date.
[INFO] (yeswehack) Data has been updated for this package.
[INFO] (yet-another-django-cart) This package is up to date.
[INFO] (yet-another-django-profiler) This package is up to date.
[INFO] (yet-another-io-channels-library) This package is up to date.
[INFO] (yet-another-runner) This package is up to date.
[INFO] (yet-another-spotify-lyrics) Data has been updated for this package.
[INFO] (yetanotherimageresizer) This package is up to date.
[INFO] (yetanotherpyoptional) This package is up to date.
[INFO] (yeti) This package is up to date.
[INFO] (yetiforce-python) This package is up to date.
[INFO] (yetship) This package is up to date.
[INFO] (yetu) This package is up to date.
[ERROR] (yev) Could not extract data from this package. See below for details.
Unsupported package directory structure.
[INFO] (yews) Data has been updated for this package.
[INFO] (yffpy) Data has been updated for this package.
[INFO] (yfi) This package is up to date.
[INFO] (yfinance) Data has been updated for this package.
[INFO] (yfinanceapi) This package is up to date.
[INFO] (yfind) This package is up to date.
[INFO] (yfj-nester) This package is up to date.
[INFO] (yfm) This package is up to date.
[INFO] (yfml) This package is up to date.
[INFO] (yfpy) Data has been updated for this package.
[INFO] (yfscraper) This package is up to date.
[INFO] (yftest) This package is up to date.
[INFO] (yftest-2) This package is up to date.
[ERROR] (yftest2) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yfx) This package is up to date.
[INFO] (yg) This package is up to date.
[INFO] (yg-emanate) This package is up to date.
[INFO] (yg-eventful) This package is up to date.
[INFO] (yg-lockfile) This package is up to date.
[INFO] (yg-thumpy) This package is up to date.
[INFO] (ygfwind-nester) This package is up to date.
[INFO] (ygg-keyfile) Data has been updated for this package.
[INFO] (yggdrasil) This package is up to date.
[INFO] (yggdrasil-framework) Data has been updated for this package.
[INFO] (yggdrasil-py) Data has been updated for this package.
[INFO] (yggtorrentscraper) Data has been updated for this package.
[INFO] (yghnester) This package is up to date.
[INFO] (ygitchangelog) Data has been updated for this package.
[INFO] (ygl) This package is up to date.
[INFO] (yglu) Data has been updated for this package.
[INFO] (ygor) This package is up to date.
[ERROR] (ygq-nester) This package does not have downloadable releases.
[INFO] (ygram) This package is up to date.
[INFO] (ygrauzdokq) This package is up to date.
[INFO] (ygrep) This package is up to date.
[INFO] (yh-catch-apple) This package is up to date.
[INFO] (yh-nester) This package is up to date.
[INFO] (yhandler) This package is up to date.
[INFO] (yhat) This package is up to date.
[INFO] (yhb) Data has been updated for this package.
[INFO] (yhnews) This package is up to date.
[INFO] (yht) This package is up to date.
[INFO] (yhttp) Data has been updated for this package.
[INFO] (yhttp-pony) Data has been updated for this package.
[INFO] (yhw-nester) This package is up to date.
[INFO] (yhwb) Data has been updated for this package.
[INFO] (yhwnester) This package is up to date.
[INFO] (yhy) This package is up to date.
[ERROR] (yi-sso-tool) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (yi-sso-tools) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yiac) Data has been updated for this package.
[INFO] (yibai-sms-python-sdk) This package is up to date.
[INFO] (yiban) Data has been updated for this package.
[INFO] (yibanapi) This package is up to date.
[INFO] (yibasuo) This package is up to date.
[INFO] (yices) This package is up to date.
[INFO] (yichin) This package is up to date.
[INFO] (yichun-shi-autocomplete) Data has been updated for this package.
[INFO] (yidashcam) This package is up to date.
[INFO] (yield) This package is up to date.
[INFO] (yield-curve-dynamics) This package is up to date.
[INFO] (yield-from) This package is up to date.
[INFO] (yield2await) This package is up to date.
[INFO] (yieldbreaker) This package is up to date.
[INFO] (yieldcurve) This package is up to date.
[INFO] (yieldcurve-vlademel) This package is up to date.
[INFO] (yieldfixture) This package is up to date.
[INFO] (yieldfrom) Data has been updated for this package.
[INFO] (yieldfrom-botocore) This package is up to date.
[INFO] (yieldfrom-http-client) This package is up to date.
[INFO] (yieldfrom-requests) This package is up to date.
[INFO] (yieldfrom-urllib-request) This package is up to date.
[INFO] (yieldfrom-urllib3) This package is up to date.
[INFO] (yieldlocus) Data has been updated for this package.
[INFO] (yieldpoints) This package is up to date.
[INFO] (yiffscraper) Data has been updated for this package.
[INFO] (yifi) This package is up to date.
[ERROR] (yify) This package does not have downloadable releases.
[INFO] (yify-sub) This package is up to date.
[INFO] (yige) This package is up to date.
[INFO] (yigemuokuai1) Data has been updated for this package.
[INFO] (yihan-helper) This package is up to date.
[INFO] (yijing) This package is up to date.
[INFO] (yikai-tools) Data has been updated for this package.
[INFO] (yima) This package is up to date.
[INFO] (yimerge) This package is up to date.
[INFO] (yimilili) This package is up to date.
[INFO] (yinan-dl) This package is up to date.
[INFO] (yincome) Data has been updated for this package.
[INFO] (yinfishs-sswitch) This package is up to date.
[INFO] (yingbox) Data has been updated for this package.
[INFO] (yingjia-common) This package is up to date.
[INFO] (yingzi) This package is up to date.
[INFO] (yinotify) This package is up to date.
[ERROR] (yinquanhui) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yinsolidated) This package is up to date.
[INFO] (yinstabot) Data has been updated for this package.
[INFO] (yinter) Data has been updated for this package.
[INFO] (yip) This package is up to date.
[INFO] (yipit) This package is up to date.
[INFO] (yippee) This package is up to date.
[INFO] (yippi) This package is up to date.
[INFO] (yipy) This package is up to date.
[INFO] (yitest) This package is up to date.
[INFO] (yith-library-server) This package is up to date.
[ERROR] (yith-web-client) This package does not have downloadable releases.
[INFO] (yiwise-time-dialogue) Data has been updated for this package.
[INFO] (yiwise-time-regex) Data has been updated for this package.
[ERROR] (yixin) This package does not have downloadable releases.
[INFO] (yixinpylib) This package is up to date.
[ERROR] (yj) This package does not have downloadable releases.
[INFO] (yj-xuniji) This package is up to date.
[INFO] (yjpproject) This package is up to date.
[INFO] (yjtest) This package is up to date.
[INFO] (yjx-nester) This package is up to date.
[INFO] (ykdl) This package is up to date.
[INFO] (ykfan-utils) Data has been updated for this package.
[INFO] (ykpers-cffi) This package is up to date.
[INFO] (ykpstools) This package is up to date.
[INFO] (yks) This package is up to date.
[INFO] (yl-app) Data has been updated for this package.
[INFO] (yl-yourname) This package is up to date.
[INFO] (yld) This package is up to date.
[INFO] (yldprolog) Data has been updated for this package.
[INFO] (yle-dl) Data has been updated for this package.
[INFO] (ylmfab) This package is up to date.
[INFO] (ylog) This package is up to date.
[INFO] (yly-python-sdk) Data has been updated for this package.
[INFO] (ym-impyla) This package is up to date.
[INFO] (ym-xadmin) Data has been updated for this package.
[INFO] (yma2txt) This package is up to date.
[ERROR] (ymake) This package does not have downloadable releases.
[INFO] (ymap) This package is up to date.
[INFO] (ymci) This package is up to date.
[INFO] (ymci-ext-acl) This package is up to date.
[INFO] (ymci-ext-coverage) This package is up to date.
[INFO] (ymci-ext-mail-alerts) This package is up to date.
[INFO] (ymci-ext-oauth) This package is up to date.
[INFO] (ymci-ext-sloccount) This package is up to date.
[INFO] (ymci-ext-source-git) This package is up to date.
[INFO] (ymci-ext-test-junit) This package is up to date.
[INFO] (ymcontent) This package is up to date.
[INFO] (ymir) This package is up to date.
[INFO] (yml) This package is up to date.
[INFO] (yml2db) This package is up to date.
[INFO] (yml2json) This package is up to date.
[ERROR] (yml2tex) Could not extract data from this package. See below for details.
"http://yml2tex.googlecode.com/files/yml2tex-1.2.tar.gz" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (ymlconfig) This package is up to date.
[INFO] (ymlf) This package is up to date.
[INFO] (ymlref) This package is up to date.
[INFO] (ymmnlputils) This package is up to date.
[INFO] (ymmsl) Data has been updated for this package.
[INFO] (ymmuimlibrary) This package is up to date.
[INFO] (ymodel) This package is up to date.
[INFO] (ymp) This package is up to date.
[INFO] (ympush) Data has been updated for this package.
[ERROR] (ymreader) This package does not have downloadable releases.
[INFO] (ymsglib) This package is up to date.
[INFO] (ymxadmin) Data has been updated for this package.
[ERROR] (ymz) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (yn) This package does not have downloadable releases.
[INFO] (yn-input) This package is up to date.
[INFO] (yn-lantern) This package is up to date.
[INFO] (ynab-api) Data has been updated for this package.
[INFO] (ynab-client) This package is up to date.
[INFO] (ynab-csv-converter) Data has been updated for this package.
[INFO] (ynab-sdk) This package is up to date.
[INFO] (ynab-weekly) Data has been updated for this package.
[INFO] (ynabamazonparser) Data has been updated for this package.
[INFO] (ynabintegrationscli) Data has been updated for this package.
[INFO] (ynabintegrationslib) Data has been updated for this package.
[INFO] (ynabinterfaceslib) Data has been updated for this package.
[INFO] (ynablib) Data has been updated for this package.
[INFO] (ynca) This package is up to date.
[ERROR] (ynester) This package does not have downloadable releases.
[INFO] (ynet) Data has been updated for this package.
[INFO] (ynitdb) Data has been updated for this package.
[INFO] (ynj) This package is up to date.
[INFO] (ynm3k) This package is up to date.
[INFO] (ynn) This package is up to date.
[INFO] (ynot) This package is up to date.
[ERROR] (yo) This package does not have downloadable releases.
[INFO] (yo-cli) This package is up to date.
[INFO] (yo-client) This package is up to date.
[INFO] (yo-ds) Data has been updated for this package.
[INFO] (yo-fabric) This package is up to date.
[INFO] (yo-fluq) Data has been updated for this package.
[INFO] (yo-fluq-ds) Data has been updated for this package.
[INFO] (yo-payments) This package is up to date.
[INFO] (yo-py) This package is up to date.
[INFO] (yo-runner) This package is up to date.
[INFO] (yoapi) This package is up to date.
[INFO] (yoav) This package is up to date.
[INFO] (yobit) This package is up to date.
[ERROR] (yobs-da) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yoc) Data has been updated for this package.
[INFO] (yoclient) This package is up to date.
[INFO] (yoconfigurator) This package is up to date.
[INFO] (yoctoec2) Data has been updated for this package.
[INFO] (yoctol-argparse) This package is up to date.
[INFO] (yoctol-keras-layer-zoo) This package is up to date.
[INFO] (yoctol-nlu) This package is up to date.
[INFO] (yoctol-utils) This package is up to date.
[INFO] (yoctools) Data has been updated for this package.
[INFO] (yoctopuce) Data has been updated for this package.
[INFO] (yoda) This package is up to date.
[ERROR] (yoda-speech) Could not extract data from this package. See below for details.
Unsupported package directory structure.
[INFO] (yoda-tools) This package is up to date.
[INFO] (yodapy) Data has been updated for this package.
[ERROR] (yodawg) This package does not have downloadable releases.
[INFO] (yodel) This package is up to date.
[INFO] (yodeploy) Data has been updated for this package.
[INFO] (yodine) Data has been updated for this package.
[INFO] (yodine-data) Data has been updated for this package.
[INFO] (yodl) This package is up to date.
[INFO] (yodlee) This package is up to date.
[INFO] (yodoit) This package is up to date.
[ERROR] (yodzpdf) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yoga) This package is up to date.
[INFO] (yogasoft) This package is up to date.
[INFO] (yogesh) This package is up to date.
[INFO] (yogesh-chandra) This package is up to date.
[INFO] (yoginth) Data has been updated for this package.
[INFO] (yogit) Data has been updated for this package.
[INFO] (yogosyu) This package is up to date.
[INFO] (yoink) This package is up to date.
[INFO] (yoinkery) This package is up to date.
[INFO] (yokadi) This package is up to date.
[INFO] (yoke) This package is up to date.
[INFO] (yolapiasync) This package is up to date.
[INFO] (yolapy) Data has been updated for this package.
[INFO] (yolk) This package is up to date.
[INFO] (yolk-portage) This package is up to date.
[INFO] (yolk1977) This package is up to date.
[INFO] (yolk3k) This package is up to date.
[INFO] (yollapay) This package is up to date.
[INFO] (yolo) This package is up to date.
[INFO] (yolo-rahul-sinha) Data has been updated for this package.
[INFO] (yolo34py) This package is up to date.
[INFO] (yolo34py-gpu) This package is up to date.
[INFO] (yolocaraccident) This package is up to date.
[INFO] (yolodb) This package is up to date.
[INFO] (yolog) This package is up to date.
[INFO] (yoloimport) This package is up to date.
[INFO] (yolov3) Data has been updated for this package.
[ERROR] (yom-client) This package does not have downloadable releases.
[INFO] (yomari) This package is up to date.
[INFO] (yomi) This package is up to date.
[INFO] (yomikata) This package is up to date.
[INFO] (yomo) This package is up to date.
[INFO] (yomopie) This package is up to date.
[INFO] (yoncrawler) Data has been updated for this package.
[INFO] (yongshuox) Data has been updated for this package.
[INFO] (yoo) This package is up to date.
[INFO] (yoongoo) This package is up to date.
[ERROR] (yoopf-for-python) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "http://bitbucket.org/yoopf/yoopf/downloads"
[INFO] (yootk-message) This package is up to date.
[INFO] (yopass-cli) This package is up to date.
[ERROR] (yopass-cli-zsolt-halo) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yopenapi) This package is up to date.
[INFO] (yopp) This package is up to date.
[INFO] (yopy) This package is up to date.
[INFO] (yopypi) This package is up to date.
[INFO] (yoqle) This package is up to date.
[INFO] (yorbay) This package is up to date.
[ERROR] (yorg) This package does not have downloadable releases.
[INFO] (yorick) This package is up to date.
[INFO] (yorkpy) This package is up to date.
[INFO] (yorkshire4) This package is up to date.
[INFO] (yorm) This package is up to date.
[INFO] (yorn) This package is up to date.
[INFO] (yos) This package is up to date.
[INFO] (yos-cube) This package is up to date.
[INFO] (yos-social-sdk) This package is up to date.
[INFO] (yosai) This package is up to date.
[INFO] (yosai-alchemystore) This package is up to date.
[INFO] (yosai-dpcache) This package is up to date.
[INFO] (yosaipy2) This package is up to date.
[INFO] (yoshix) This package is up to date.
[INFO] (yoso) This package is up to date.
[INFO] (yospacecds) This package is up to date.
[ERROR] (yosstheboss) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (yossthebossgstat) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yosstocks) This package is up to date.
[INFO] (yosun) This package is up to date.
[INFO] (yota) This package is up to date.
[INFO] (yotest) Data has been updated for this package.
[ERROR] (yothisisareallylongname) This package does not have downloadable releases.
[INFO] (yoti) Data has been updated for this package.
[INFO] (yoton) This package is up to date.
[ERROR] (yotsuba) Could not extract data from this package. See below for details.
"http://yotsuba.googlecode.com/files/yotsuba-3.1.tar.gz" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yotta) Data has been updated for this package.
[INFO] (yotuyu) Data has been updated for this package.
[INFO] (you) This package is up to date.
[INFO] (you-get) Data has been updated for this package.
[INFO] (youarehere) Data has been updated for this package.
[INFO] (youchoose) This package is up to date.
[INFO] (youda) This package is up to date.
[INFO] (youdao) This package is up to date.
[INFO] (youdao-dict) This package is up to date.
[INFO] (youdao-python) This package is up to date.
[INFO] (youdao-simple) This package is up to date.
[INFO] (youdao-tr-free) Data has been updated for this package.
[INFO] (youdao-wd) This package is up to date.
[INFO] (youdaodict) This package is up to date.
[INFO] (youdaofanyi) This package is up to date.
[INFO] (youdaotranslate) Data has been updated for this package.
[INFO] (youku) Data has been updated for this package.
[INFO] (youkudownloader) This package is up to date.
[INFO] (yould) This package is up to date.
[INFO] (youless-python-bridge) This package is up to date.
[INFO] (youlldownload) This package is up to date.
[INFO] (youmadeit) This package is up to date.
[INFO] (youmeng) Data has been updated for this package.
[ERROR] (younet-rnd-infrastructure) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (young) This package is up to date.
[INFO] (young-tools) This package is up to date.
[INFO] (younggis) This package is up to date.
[INFO] (youngho) This package is up to date.
[INFO] (youngho2016) This package is up to date.
[INFO] (youngmenpackage) This package is up to date.
[INFO] (youngshine-nester) This package is up to date.
[INFO] (youngtest) Data has been updated for this package.
[INFO] (younit) This package is up to date.
[INFO] (younited) Data has been updated for this package.
[INFO] (younitedlib) Data has been updated for this package.
[INFO] (youplay) This package is up to date.
[INFO] (your-app) This package is up to date.
[INFO] (your-notes) This package is up to date.
[INFO] (yourai) This package is up to date.
[INFO] (yourface) This package is up to date.
[INFO] (yourls) This package is up to date.
[INFO] (yourmum) Data has been updated for this package.
[INFO] (yourproject) Data has been updated for this package.
[INFO] (yourtool) This package is up to date.
[INFO] (youscan) Data has been updated for this package.
[INFO] (yousub) This package is up to date.
[INFO] (youtiao) This package is up to date.
[INFO] (youtokentome) Data has been updated for this package.
[INFO] (youtrack) Data has been updated for this package.
[INFO] (youtrack-rest-api) This package is up to date.
[INFO] (youtrack-scripts) Data has been updated for this package.
[ERROR] (youtube) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (youtube-api) This package does not have downloadable releases.
[INFO] (youtube-api-wrapper) This package is up to date.
[INFO] (youtube-archive) This package is up to date.
[INFO] (youtube-audio-downloader) This package is up to date.
[INFO] (youtube-autodownloader) This package is up to date.
[INFO] (youtube-batch) This package is up to date.
[INFO] (youtube-cli) This package is up to date.
[INFO] (youtube-cue) This package is up to date.
[INFO] (youtube-curses) This package is up to date.
[INFO] (youtube-data-api) Data has been updated for this package.
[INFO] (youtube-data-api3) This package is up to date.
[ERROR] (youtube-de-locke) Could not extract data from this package. See below for details.
"https://files.pythonhosted.org/packages/6b/c6/d0c78ad782f0635d39f902a7721117383861cf6e35ca73222a6054ebc7d3/youtube%20de%20locke-1.0.0.tar.gz" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (youtube-django) This package is up to date.
[INFO] (youtube-dl) Data has been updated for this package.
[INFO] (youtube-dl-plugin) This package is up to date.
[INFO] (youtube-dl-server) This package is up to date.
[INFO] (youtube-dlg) This package is up to date.
[INFO] (youtube-download) Data has been updated for this package.
[INFO] (youtube-extract) Data has been updated for this package.
[INFO] (youtube-livechat-messages) This package is up to date.
[INFO] (youtube-loader) This package is up to date.
[INFO] (youtube-me) This package is up to date.
[INFO] (youtube-metrics) This package is up to date.
[INFO] (youtube-mp3) This package is up to date.
[INFO] (youtube-mp3-downloader) This package is up to date.
[INFO] (youtube-multi-dl) Data has been updated for this package.
[INFO] (youtube-playlist-downloader) Data has been updated for this package.
[INFO] (youtube-python) This package is up to date.
[INFO] (youtube-python-sdk) This package is up to date.
[INFO] (youtube-scraper) Data has been updated for this package.
[INFO] (youtube-search) Data has been updated for this package.
[INFO] (youtube-sentiment) This package is up to date.
[INFO] (youtube-sm) Data has been updated for this package.
[INFO] (youtube-sm-parser) Data has been updated for this package.
[INFO] (youtube-song-downloader) This package is up to date.
[INFO] (youtube-streamer) This package is up to date.
[INFO] (youtube-title-parse) This package is up to date.
[INFO] (youtube-title-parser) This package is up to date.
[INFO] (youtube-to-mpd) This package is up to date.
[INFO] (youtube-transcript-api) Data has been updated for this package.
[INFO] (youtube-unofficial) This package is up to date.
[ERROR] (youtube-upload) This package does not have downloadable releases.
[INFO] (youtube-video-upload) This package is up to date.
[INFO] (youtube-watcher) This package is up to date.
[INFO] (youtube2m4a) Data has been updated for this package.
[INFO] (youtube2mp3) Data has been updated for this package.
[ERROR] (youtube2srt) This package does not have downloadable releases.
[INFO] (youtube2zim) Data has been updated for this package.
[INFO] (youtube3) Data has been updated for this package.
[INFO] (youtubeapi) Data has been updated for this package.
[INFO] (youtubeapi-tjmoon0104) Data has been updated for this package.
[INFO] (youtubecomments) This package is up to date.
[INFO] (youtubedata) Data has been updated for this package.
[ERROR] (youtubedl) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (youtubesentimentanalysis) Data has been updated for this package.
[INFO] (youtubetaggenerator) Data has been updated for this package.
[INFO] (youtubetomp3) This package is up to date.
[INFO] (youtubetranscript) This package is up to date.
[ERROR] (youtubevlc) This package does not have downloadable releases.
[INFO] (youtubewatched) This package is up to date.
[INFO] (youtunes) This package is up to date.
[INFO] (youtux-test-travis) This package is up to date.
[INFO] (youversion) Data has been updated for this package.
[INFO] (youzan) This package is up to date.
[INFO] (youzhang) This package is up to date.
[INFO] (yowlayer-django-store) This package is up to date.
[INFO] (yowsup) This package is up to date.
[INFO] (yowsup-celery) This package is up to date.
[INFO] (yowsup-gateway) This package is up to date.
[INFO] (yowsup2) This package is up to date.
[ERROR] (yoyo) This package does not have downloadable releases.
[INFO] (yoyo-database-migrations) This package is up to date.
[INFO] (yoyo-distributions) Data has been updated for this package.
[INFO] (yoyo-indexima) Data has been updated for this package.
[INFO] (yoyo-migrations) This package is up to date.
[ERROR] (yoyo-submarine) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yoyolala) This package is up to date.
[ERROR] (yoyomigrations) This package does not have downloadable releases.
[INFO] (yoyopkg) This package is up to date.
[INFO] (yoyotestpags00) This package is up to date.
[INFO] (yozuch) This package is up to date.
[INFO] (ypackage) Data has been updated for this package.
[INFO] (ypassbook) This package is up to date.
[INFO] (ypc) Data has been updated for this package.
[INFO] (ypcc) This package is up to date.
[INFO] (ypconfig) This package is up to date.
[INFO] (ypconnector) This package is up to date.
[INFO] (ypcspy) This package is up to date.
[INFO] (ypdd) This package is up to date.
[INFO] (ypersms-client) This package is up to date.
[INFO] (ypgame) This package is up to date.
[INFO] (yphtest) This package is up to date.
[INFO] (ypinyin) This package is up to date.
[ERROR] (ypipe) Could not extract data from this package. See below for details.
"https://ypipe.googlecode.com/files/ypipe-0.8.tar.gz" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (ypiptest) This package is up to date.
[INFO] (ypkpathway) This package is up to date.
[INFO] (yplan-logging-utils) This package is up to date.
[INFO] (ypotf) This package is up to date.
[INFO] (ypredict) This package is up to date.
[INFO] (ypstruct) This package is up to date.
[INFO] (ypy) This package is up to date.
[INFO] (yq) Data has been updated for this package.
[ERROR] (yqf) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yqhoutest) Data has been updated for this package.
[INFO] (yql) This package is up to date.
[INFO] (yql-finance) This package is up to date.
[INFO] (yqmd) This package is up to date.
[INFO] (yqmiot) This package is up to date.
[INFO] (yqmq) This package is up to date.
[INFO] (yqt) This package is up to date.
[INFO] (yr) This package is up to date.
[INFO] (yrequests) This package is up to date.
[INFO] (yrest) This package is up to date.
[INFO] (ys-nester1) This package is up to date.
[INFO] (ys-service) Data has been updated for this package.
[INFO] (ysa) This package is up to date.
[INFO] (ysanic) This package is up to date.
[INFO] (yschema) This package is up to date.
[INFO] (yserv) This package is up to date.
[ERROR] (ysfile) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yshen-setup-test) This package is up to date.
[INFO] (yshysh) This package is up to date.
[INFO] (ysmtool) This package is up to date.
[INFO] (yson) This package is up to date.
[INFO] (yspacepy) Data has been updated for this package.
[INFO] (yspec) Data has been updated for this package.
[INFO] (ystocklist) This package is up to date.
[INFO] (ystockquote) This package is up to date.
[INFO] (yt) This package is up to date.
[INFO] (yt-archiver) This package is up to date.
[INFO] (yt-astro-analysis) This package is up to date.
[INFO] (yt-finance) This package is up to date.
[INFO] (yt-formula-node) This package is up to date.
[INFO] (yt-helper) Data has been updated for this package.
[INFO] (yt-iframe) This package is up to date.
[INFO] (yt-info) This package is up to date.
[INFO] (yt-interaction) This package is up to date.
[INFO] (yt-lib) Data has been updated for this package.
[INFO] (yt-rank-checker) This package is up to date.
[INFO] (yt-recipe-relativeworkaround) This package is up to date.
[INFO] (yt-recipe-shell) This package is up to date.
[INFO] (yt-search) Data has been updated for this package.
[INFO] (yt-songs) This package is up to date.
[INFO] (yt-videos-list) Data has been updated for this package.
[INFO] (yt2mp3) This package is up to date.
[INFO] (ytapi) Data has been updated for this package.
[INFO] (ytb) This package is up to date.
[INFO] (ytbdwn) This package is up to date.
[INFO] (ytclient) This package is up to date.
[INFO] (ytdata) This package is up to date.
[INFO] (ytdown) This package is up to date.
[INFO] (ytdownloader) This package is up to date.
[INFO] (ytdvideo) This package is up to date.
[INFO] (ytelapi) This package is up to date.
[INFO] (yter) This package is up to date.
[INFO] (ytermplayer) This package is up to date.
[INFO] (ytest) This package is up to date.
[INFO] (ytfs) This package is up to date.
[INFO] (ytgrep) Data has been updated for this package.
[INFO] (ytiny) This package is up to date.
[INFO] (ytlog) This package is up to date.
[INFO] (ytmdl) Data has been updated for this package.
[INFO] (ytmpc) This package is up to date.
[INFO] (ytool) Data has been updated for this package.
[INFO] (ytools) This package is up to date.
[INFO] (ytopt) This package is up to date.
[ERROR] (ytp) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (ytp1) This package is up to date.
[INFO] (ytrans) This package is up to date.
[INFO] (ytranslate) This package is up to date.
[INFO] (ytree) Data has been updated for this package.
[INFO] (ytreviewsapi) Data has been updated for this package.
[INFO] (ytrie) This package is up to date.
[INFO] (ytrpdf) This package is up to date.
[INFO] (ytrss) This package is up to date.
[INFO] (yts) This package is up to date.
[INFO] (yts-downloader) Data has been updated for this package.
[INFO] (ytsapi) Data has been updated for this package.
[INFO] (ytsearch) This package is up to date.
[INFO] (ytsearch-develop) This package is up to date.
[INFO] (ytsingleton) This package is up to date.
[ERROR] (ytsnarf) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (ytsr) This package is up to date.
[INFO] (ytsub) This package is up to date.
[INFO] (ytsubtitles) Data has been updated for this package.
[INFO] (ytu) Data has been updated for this package.
[INFO] (yturl) This package is up to date.
[INFO] (ytvpn) This package is up to date.
[INFO] (ytzoo) This package is up to date.
[INFO] (yu) This package is up to date.
[INFO] (yu-nester) This package is up to date.
[INFO] (yuan) This package is up to date.
[INFO] (yuankq) This package is up to date.
[INFO] (yuanmaxiong1) Data has been updated for this package.
[INFO] (yubiadmin) This package is up to date.
[INFO] (yubiauth) This package is up to date.
[INFO] (yubico) This package is up to date.
[ERROR] (yubico-authenticator) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yubico-bitcoin) This package is up to date.
[INFO] (yubico-client) Data has been updated for this package.
[INFO] (yubicoclient) This package is up to date.
[INFO] (yubihsm) This package is up to date.
[INFO] (yubikey) This package is up to date.
[INFO] (yubikey-manager) Data has been updated for this package.
[INFO] (yubikey-neo-manager) This package is up to date.
[INFO] (yubikey-piv-manager) This package is up to date.
[INFO] (yubikey-totp-gui) This package is up to date.
[INFO] (yubin) Data has been updated for this package.
[INFO] (yubioath-desktop) This package is up to date.
[INFO] (yubiotp) Data has been updated for this package.
[INFO] (yubistack) This package is up to date.
[INFO] (yubistorm) This package is up to date.
[INFO] (yucc) Data has been updated for this package.
[INFO] (yuce) Data has been updated for this package.
[INFO] (yuci-dictionary) This package is up to date.
[ERROR] (yuck) This package does not have downloadable releases.
[INFO] (yudu) This package is up to date.
[INFO] (yuejzdemo) Data has been updated for this package.
[INFO] (yufeng-test) Data has been updated for this package.
[INFO] (yufou) This package is up to date.
[INFO] (yugabyte-pycommon) This package is up to date.
[INFO] (yugioh-bot) This package is up to date.
[INFO] (yuicompressor) This package is up to date.
[INFO] (yuid) This package is up to date.
[INFO] (yujia-nester) This package is up to date.
[INFO] (yujiamath) Data has been updated for this package.
[INFO] (yujin-tools) This package is up to date.
[INFO] (yuki) This package is up to date.
[INFO] (yuleak-api) Data has been updated for this package.
[INFO] (yulelog) This package is up to date.
[INFO] (yulonglib) This package is up to date.
[ERROR] (yum-repos) This package does not have downloadable releases.
[INFO] (yum2s3) This package is up to date.
[INFO] (yum4fit-halfdeadpie) This package is up to date.
[INFO] (yuma) Data has been updated for this package.
[INFO] (yumemi) This package is up to date.
[INFO] (yumi-nester) This package is up to date.
[INFO] (yuml) This package is up to date.
[INFO] (yummly) This package is up to date.
[ERROR] (yummy) This package does not have downloadable releases.
[INFO] (yummy-sphinx-theme) Data has been updated for this package.
[INFO] (yumpu-sdk) This package is up to date.
[INFO] (yumrepos) This package is up to date.
[INFO] (yumwat) This package is up to date.
[INFO] (yuna) This package is up to date.
[ERROR] (yunant) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yunbi) This package is up to date.
[INFO] (yunbk) This package is up to date.
[INFO] (yundama) Data has been updated for this package.
[INFO] (yunetkomax) This package is up to date.
[INFO] (yunetkomymath) This package is up to date.
[INFO] (yunguanfu-mil3id2019) Data has been updated for this package.
[INFO] (yuniteapi) Data has been updated for this package.
[INFO] (yunlib) This package is up to date.
[INFO] (yunomi) This package is up to date.
[INFO] (yunorm) This package is up to date.
[INFO] (yunpian) This package is up to date.
[INFO] (yunpian-python-sdk) This package is up to date.
[INFO] (yunpian-sdk-python) This package is up to date.
[INFO] (yunpipe) This package is up to date.
[INFO] (yunpipe2) This package is up to date.
[INFO] (yunti) This package is up to date.
[ERROR] (yuntian-nester) This package does not have downloadable releases.
[INFO] (yuntongxun) This package is up to date.
[INFO] (yuntongxun-restapi-asyncio) This package is up to date.
[INFO] (yup) This package is up to date.
[ERROR] (yup-python) This package does not have downloadable releases.
[INFO] (yupeifeng-nester) This package is up to date.
[INFO] (yupp) This package is up to date.
[INFO] (yuque-py) Data has been updated for this package.
[INFO] (yur) This package is up to date.
[INFO] (yuriko) This package is up to date.
[INFO] (yurl) This package is up to date.
[INFO] (yurlungur) This package is up to date.
[INFO] (yurual-test1) This package is up to date.
[INFO] (yusssstd) This package is up to date.
[INFO] (yutest) This package is up to date.
[INFO] (yutils) Data has been updated for this package.
[ERROR] (yuting-recu) This package does not have downloadable releases.
[ERROR] (yuting-recu-now) This package does not have downloadable releases.
[INFO] (yutu) This package is up to date.
[INFO] (yuu) Data has been updated for this package.
[INFO] (yuuno) This package is up to date.
[INFO] (yuuno-core) This package is up to date.
[INFO] (yux-nester) This package is up to date.
[INFO] (yuzhuhwbubbler) Data has been updated for this package.
[INFO] (yuzihua-bolg) This package is up to date.
[INFO] (yw-aut) This package is up to date.
[INFO] (yw-nester) This package is up to date.
[INFO] (ywaut) This package is up to date.
[INFO] (ywbde1124) This package is up to date.
[INFO] (ywdblogmath) This package is up to date.
[INFO] (ywdblogmath2) This package is up to date.
[INFO] (yweather) This package is up to date.
[INFO] (ywfnester) This package is up to date.
[INFO] (ywh2bt) Data has been updated for this package.
[INFO] (ywkd-tools) Data has been updated for this package.
[INFO] (yworklog) This package is up to date.
[INFO] (yx-nest) This package is up to date.
[INFO] (yxh-ip-address) Data has been updated for this package.
[INFO] (yxj-yourname) This package is up to date.
[INFO] (yxlogging) Data has been updated for this package.
[INFO] (yxpy) This package is up to date.
[INFO] (yxs-required) This package is up to date.
[INFO] (yxspkg) Data has been updated for this package.
[ERROR] (yxspkg-binary) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yxspkg-data-faceswap) This package is up to date.
[INFO] (yxspkg-data-icon) This package is up to date.
[INFO] (yxspkg-encrypt) This package is up to date.
[INFO] (yxspkg-pip) This package is up to date.
[INFO] (yxspkg-songzgif) This package is up to date.
[INFO] (yxspkg-songzviewer) This package is up to date.
[INFO] (yxspkg-tecfile) This package is up to date.
[ERROR] (yxspkg-vscrun) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yxspkg-wget) This package is up to date.
[ERROR] (yxstool) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yxt-nlp-toolkit) This package is up to date.
[INFO] (yxtest) This package is up to date.
[INFO] (yxwaiter) Data has been updated for this package.
[INFO] (yy) This package is up to date.
[INFO] (yy-nester) This package is up to date.
[INFO] (yy-spider) This package is up to date.
[ERROR] (yyafl) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "http://dl.stackfoundry.org/yyafl/"
[INFO] (yyggtest) Data has been updated for this package.
[ERROR] (yyhnester) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (yyhtools) This package is up to date.
[INFO] (yyimg) Data has been updated for this package.
[INFO] (yylnester) This package is up to date.
[INFO] (yynb) This package is up to date.
[INFO] (yypget) This package is up to date.
[INFO] (yyq-print) This package is up to date.
[INFO] (yyqq188-mydemo) This package is up to date.
[INFO] (yyreview) This package is up to date.
[INFO] (yytest) Data has been updated for this package.
[INFO] (yyxmath) This package is up to date.
[INFO] (yzal) This package is up to date.
[INFO] (yzconfig) This package is up to date.
[INFO] (yzgprinter) This package is up to date.
[INFO] (yzj-athletelist) This package is up to date.
[INFO] (yzj-athletemodel) This package is up to date.
[INFO] (yzj-sanitize) This package is up to date.
[INFO] (yznester) This package is up to date.
[INFO] (yzs-work) Data has been updated for this package.
[INFO] (yzwspider) Data has been updated for this package.
[INFO] 
[INFO] 
[INFO] Total packages: 1573
[INFO]     Packages processed: 1573
[INFO]         Packages updated: 352
[INFO]         Packages up-to-date: 1122
[INFO]         Packages without response: 36
[INFO]         Packages without urls: 0
[INFO]         Packages without downloads: 46
[INFO]         Packages with data errors: 17
[INFO]     Packages not processed: 0
[INFO] 
[INFO] 
[INFO] Ending execution.
