[INFO] Starting execution.
[INFO] Downloading package list from PyPI ...
[ERROR] (u) This package does not have downloadable releases.
[ERROR] (u-cli) This package does not have downloadable releases.
[INFO] (u-msgpack-python) Data has been updated for this package.
[INFO] (u1-test-utils) This package is up to date.
[INFO] (u1db) This package is up to date.
[INFO] (u2fval) This package is up to date.
[INFO] (u2fval-client) This package is up to date.
[INFO] (u2parser) This package is up to date.
[INFO] (u2py) This package is up to date.
[INFO] (ua-api-utils) This package is up to date.
[INFO] (ua-clarity-api) Data has been updated for this package.
[INFO] (ua-clarity-tools) Data has been updated for this package.
[INFO] (ua-generic-rest-api) Data has been updated for this package.
[INFO] (ua-ilab-tools) Data has been updated for this package.
[INFO] (ua-parser) This package is up to date.
[INFO] (ua-parser-next) This package is up to date.
[INFO] (ua-project-transfer) Data has been updated for this package.
[INFO] (ua-spoofer) Data has been updated for this package.
[INFO] (ua-stache-api) Data has been updated for this package.
[INFO] (ua2-ajax) This package is up to date.
[INFO] (ua2-carbon) This package is up to date.
[INFO] (ua2-celery) This package is up to date.
[INFO] (ua2-djfab) This package is up to date.
[INFO] (ua2-fabdep) This package is up to date.
[INFO] (ua2-forms) This package is up to date.
[INFO] (ua2-jsondoc) This package is up to date.
[INFO] (ua2-mongolog) This package is up to date.
[INFO] (ua2-otl) This package is up to date.
[INFO] (ua2-patch) This package is up to date.
[INFO] (ua2-redis) This package is up to date.
[INFO] (ua2-table3) This package is up to date.
[INFO] (ua2-table3a) This package is up to date.
[INFO] (ua2nx) Data has been updated for this package.
[INFO] (uaconnect) This package is up to date.
[ERROR] (uacs1) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (uadetector) This package is up to date.
[INFO] (uadevice) Data has been updated for this package.
[INFO] (uadm) This package is up to date.
[INFO] (uagent) This package is up to date.
[INFO] (uam) This package is up to date.
[INFO] (uamconfig-cli) This package is up to date.
[INFO] (uamd) This package is up to date.
[INFO] (uamobile) This package is up to date.
[INFO] (uamqp) Data has been updated for this package.
[INFO] (uao) This package is up to date.
[INFO] (uaparser) This package is up to date.
[INFO] (uapycon) This package is up to date.
[INFO] (uarango) This package is up to date.
[INFO] (uareach) Data has been updated for this package.
[ERROR] (uarm) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (uarm4py) This package is up to date.
[INFO] (uarray) Data has been updated for this package.
[INFO] (uart) This package is up to date.
[INFO] (uart-debugger) Data has been updated for this package.
[INFO] (uartis) This package is up to date.
[INFO] (uasparser2) This package is up to date.
[INFO] (uavcan) This package is up to date.
[INFO] (uaverify) This package is up to date.
[INFO] (uaviak-timetable) Data has been updated for this package.
[INFO] (uavro) This package is up to date.
[INFO] (uavsim) This package is up to date.
[INFO] (ub-object-client) This package is up to date.
[INFO] (ub-paste) This package is up to date.
[INFO] (ub-split-map) This package is up to date.
[INFO] (ubackup) This package is up to date.
[INFO] (ubak) This package is up to date.
[INFO] (ubcd) This package is up to date.
[INFO] (ubcpi-xblock) This package is up to date.
[INFO] (ubcs-auxiliary) Data has been updated for this package.
[INFO] (ube) This package is up to date.
[INFO] (ubelt) Data has been updated for this package.
[INFO] (uber) This package is up to date.
[INFO] (uber-cli) This package is up to date.
[INFO] (uber-py) This package is up to date.
[INFO] (uber-rides) This package is up to date.
[INFO] (uberapi) This package is up to date.
[INFO] (uberdict) This package is up to date.
[INFO] (uberdoc) This package is up to date.
[INFO] (uberfare) This package is up to date.
[INFO] (uberlogging) Data has been updated for this package.
[INFO] (uberlogs) This package is up to date.
[INFO] (ubermag) Data has been updated for this package.
[INFO] (ubermagtable) Data has been updated for this package.
[INFO] (ubermagutil) Data has been updated for this package.
[INFO] (uberon-py) This package is up to date.
[INFO] (uberping) This package is up to date.
[INFO] (uberpong) This package is up to date.
[INFO] (uberpy) This package is up to date.
[INFO] (ubersicht) This package is up to date.
[INFO] (ubersmith) This package is up to date.
[INFO] (ubersmith-remote-module-server) This package is up to date.
[INFO] (uberspace-takeout) Data has been updated for this package.
[INFO] (uberspace-templates) This package is up to date.
[INFO] (ubgrade) Data has been updated for this package.
[INFO] (ubi-config) Data has been updated for this package.
[INFO] (ubi-population-tool) Data has been updated for this package.
[INFO] (ubi-reader) Data has been updated for this package.
[INFO] (ubidots) This package is up to date.
[INFO] (ubidots-global-cache) This package is up to date.
[INFO] (ubik) This package is up to date.
[INFO] (ubiltools) Data has been updated for this package.
[INFO] (ubindex) This package is up to date.
[INFO] (ubindrzvyo) This package is up to date.
[INFO] (ubiome) This package is up to date.
[INFO] (ubiquerg) Data has been updated for this package.
[INFO] (ubirch-protocol) Data has been updated for this package.
[INFO] (ubirch-python-utils) This package is up to date.
[INFO] (ubit-kernel) This package is up to date.
[INFO] (ubittool) This package is up to date.
[INFO] (ubjsonstream) This package is up to date.
[ERROR] (ubjspy) This package does not have downloadable releases.
[ERROR] (ubl) This package does not have downloadable releases.
[INFO] (ublcii) Data has been updated for this package.
[INFO] (ublox) This package is up to date.
[INFO] (ublox-lara-r2) This package is up to date.
[INFO] (ubm) This package is up to date.
[INFO] (uboat) This package is up to date.
[INFO] (uboot) Data has been updated for this package.
[INFO] (ubot) This package is up to date.
[ERROR] (ubrew) This package does not have downloadable releases.
[INFO] (ubscrape) Data has been updated for this package.
[INFO] (ubuild) This package is up to date.
[ERROR] (ubuntu) This package does not have downloadable releases.
[INFO] (ubuntu-bug-triage) This package is up to date.
[INFO] (ubuntu-cloud-image) This package is up to date.
[INFO] (ubuntu-iso-download) This package is up to date.
[INFO] (ubuntu-netspeed) This package is up to date.
[INFO] (ubuntu-release-info) This package is up to date.
[INFO] (ubuntuami) This package is up to date.
[INFO] (ubuntudesign-asset-mapper) This package is up to date.
[INFO] (ubuntudesign-documentation-builder) This package is up to date.
[INFO] (ubuntudesign-gsa) This package is up to date.
[INFO] (ubuntufinder) This package is up to date.
[INFO] (ubuntui) This package is up to date.
[INFO] (ubuntuone-storageprotocol) This package is up to date.
[INFO] (ubuntupaste) This package is up to date.
[INFO] (ubus) This package is up to date.
[INFO] (ubxserial) Data has been updated for this package.
[INFO] (ubxtranslator) This package is up to date.
[INFO] (uc) This package is up to date.
[INFO] (uc-chalk-rip) This package is up to date.
[INFO] (ucache) Data has been updated for this package.
[INFO] (ucal) Data has been updated for this package.
[ERROR] (ucam-dsm) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (ucam-managed-mac-utils) Data has been updated for this package.
[INFO] (ucam-wls) This package is up to date.
[INFO] (ucamcl) Data has been updated for this package.
[INFO] (ucamdsm) Data has been updated for this package.
[INFO] (ucanlintools) This package is up to date.
[INFO] (ucansystec) This package is up to date.
[INFO] (ucas-dm) This package is up to date.
[INFO] (ucas-wifi) Data has been updated for this package.
[INFO] (ucasort) This package is up to date.
[INFO] (ucca) Data has been updated for this package.
[INFO] (ucdev) This package is up to date.
[INFO] (uceasy) Data has been updated for this package.
[INFO] (ucenter-sdk) Data has been updated for this package.
[INFO] (ucf-options-base) This package is up to date.
[INFO] (ucflib) This package is up to date.
[INFO] (ucg) This package is up to date.
[ERROR] (ucgc-commons) This package does not have downloadable releases.
[INFO] (uchicago-cs-setup-script) Data has been updated for this package.
[INFO] (uchroot) This package is up to date.
[INFO] (uci-net) Data has been updated for this package.
[INFO] (uciconfig) This package is up to date.
[INFO] (ucis4eq) This package is up to date.
[INFO] (ucitests) This package is up to date.
[INFO] (ucivms) This package is up to date.
[INFO] (uciwebauth) Data has been updated for this package.
[INFO] (ucl) This package is up to date.
[INFO] (ucla-cs118) This package is up to date.
[INFO] (uclassify) This package is up to date.
[INFO] (uclassify-sc) This package is up to date.
[INFO] (uclcoin) This package is up to date.
[ERROR] (uclean) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (ucli) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "http://pypi.python.org/pypi/ucloud-cli"
[INFO] (uclime) This package is up to date.
[INFO] (uclmr-jack) This package is up to date.
[INFO] (ucloud) This package is up to date.
[INFO] (ucloud-cli) This package is up to date.
[INFO] (ucloud-client) This package is up to date.
[INFO] (ucloud-common) Data has been updated for this package.
[INFO] (ucloud-py) This package is up to date.
[INFO] (ucloud-sdk-python2) Data has been updated for this package.
[INFO] (ucloud-sdk-python3) Data has been updated for this package.
[INFO] (ucloud-storage-python-wrapper) This package is up to date.
[ERROR] (ucloud-ufile) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (ucloudbiz) This package is up to date.
[ERROR] (ucloudcli) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (ucloudclient) This package is up to date.
[INFO] (ucltip) This package is up to date.
[INFO] (ucmclient) This package is up to date.
[INFO] (ucms) Data has been updated for this package.
[INFO] (ucmscraper) Data has been updated for this package.
[INFO] (ucnn) This package is up to date.
[ERROR] (ucnum) This package does not have downloadable releases.
[INFO] (ucnumber) This package is up to date.
[INFO] (ucoinpy) This package is up to date.
[INFO] (ucom-eli) This package is up to date.
[INFO] (ucommander) This package is up to date.
[INFO] (uconf) This package is up to date.
[INFO] (uconfig) This package is up to date.
[INFO] (uconfload) This package is up to date.
[INFO] (uconnmlhi-ukbiobankproject) This package is up to date.
[INFO] (uconnrcmpy) This package is up to date.
[INFO] (ucopy) Data has been updated for this package.
[INFO] (ucp) This package is up to date.
[ERROR] (ucp-pkg-zhamri) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (ucp9) Data has been updated for this package.
[INFO] (ucpbased) This package is up to date.
[ERROR] (ucpbased-pkg-zhamri) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (ucpyr) This package is up to date.
[INFO] (ucrc) Data has been updated for this package.
[INFO] (ucrdtw) This package is up to date.
[INFO] (ucron) This package is up to date.
[INFO] (ucrspawner) This package is up to date.
[INFO] (ucrypt) This package is up to date.
[INFO] (ucs) This package is up to date.
[INFO] (ucsc-genomes-downloader) Data has been updated for this package.
[INFO] (ucsc-snapshots) This package is up to date.
[INFO] (ucscgenome) This package is up to date.
[INFO] (ucscsdk) This package is up to date.
[INFO] (ucscsession) This package is up to date.
[ERROR] (ucsctools) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (ucsdyelpdata) This package is up to date.
[ERROR] (ucsm-gui) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (ucsmsdk) Data has been updated for this package.
[INFO] (ucsmsdk-samples) This package is up to date.
[INFO] (ucssdk) This package is up to date.
[INFO] (ucsv) This package is up to date.
[INFO] (uctb) Data has been updated for this package.
[INFO] (uctenkovkapy) This package is up to date.
[INFO] (uctfd) This package is up to date.
[INFO] (uctools) Data has been updated for this package.
[INFO] (ucuenca) This package is up to date.
[INFO] (ucumos) Data has been updated for this package.
[INFO] (ucwa) This package is up to date.
[ERROR] (ucxpy) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (ud) This package is up to date.
[INFO] (ud-django-meta) This package is up to date.
[INFO] (ud-py-moneyed) This package is up to date.
[INFO] (ud-toolkit) This package is up to date.
[INFO] (ud2ude) Data has been updated for this package.
[INFO] (ud2ude-aryehgigi) Data has been updated for this package.
[INFO] (ud4d) This package is up to date.
[INFO] (udacity) This package is up to date.
[INFO] (udacity-carndt1test) This package is up to date.
[INFO] (udacity-chiron) This package is up to date.
[INFO] (udacity-dl) This package is up to date.
[INFO] (udacity-gaussian-binomial-distributions) Data has been updated for this package.
[INFO] (udacity-pa) Data has been updated for this package.
[INFO] (udacitymle-distributions) Data has been updated for this package.
[INFO] (udapi) This package is up to date.
[INFO] (udaswissknife) Data has been updated for this package.
[INFO] (udata) Data has been updated for this package.
[INFO] (udata-ckan) Data has been updated for this package.
[INFO] (udata-croquemort) This package is up to date.
[INFO] (udata-data-fair) This package is up to date.
[INFO] (udata-geoplatform) This package is up to date.
[INFO] (udata-gouvfr) Data has been updated for this package.
[ERROR] (udata-harvest) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (udata-koumoul) This package is up to date.
[INFO] (udata-ldap) This package is up to date.
[INFO] (udata-ods) This package is up to date.
[INFO] (udata-piwik) Data has been updated for this package.
[INFO] (udata-recommendations) This package is up to date.
[INFO] (udata-tabular-preview) This package is up to date.
[INFO] (udata-youckan) This package is up to date.
[INFO] (udatastore) This package is up to date.
[INFO] (udatetime) This package is up to date.
[INFO] (udaypdf) This package is up to date.
[ERROR] (udb) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (udb-py) Data has been updated for this package.
[INFO] (udbnn) This package is up to date.
[INFO] (udc-dsnd-distributions) This package is up to date.
[INFO] (udebugcli) This package is up to date.
[INFO] (udemy) Data has been updated for this package.
[INFO] (udemy-dl) This package is up to date.
[INFO] (udemy-dl2) This package is up to date.
[INFO] (udemydl) This package is up to date.
[INFO] (udevbackup) This package is up to date.
[INFO] (udger) Data has been updated for this package.
[INFO] (udica) Data has been updated for this package.
[INFO] (udicopendata) This package is up to date.
[INFO] (udict) Data has been updated for this package.
[INFO] (udictfidf) This package is up to date.
[INFO] (udictoolkits) This package is up to date.
[ERROR] (udictoolkits-01) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (udiskie) Data has been updated for this package.
[INFO] (udkanbun) Data has been updated for this package.
[INFO] (udkm1dsim) Data has been updated for this package.
[INFO] (udkundoku) Data has been updated for this package.
[ERROR] (udl) Could not extract data from this package. See below for details.
"https://github.com/Arpitbhawar/Udacity-Course-Downloader.git/tarball/master" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (udm) This package is up to date.
[INFO] (udm-rest-client) Data has been updated for this package.
[INFO] (udmx-pyusb) This package is up to date.
[INFO] (udn-cis-client) This package is up to date.
[INFO] (udnn) This package is up to date.
[INFO] (udns) This package is up to date.
[INFO] (udo) This package is up to date.
[INFO] (udoc) This package is up to date.
[INFO] (udocker) This package is up to date.
[INFO] (udocker-stimela) This package is up to date.
[INFO] (udon) Data has been updated for this package.
[ERROR] (udoolib) This package does not have downloadable releases.
[INFO] (udownmark) This package is up to date.
[INFO] (udp-filetransfer) Data has been updated for this package.
[INFO] (udp-test) This package is up to date.
[INFO] (udpbot) Data has been updated for this package.
[INFO] (udpcp) This package is up to date.
[INFO] (udplog) This package is up to date.
[INFO] (udplogger) This package is up to date.
[INFO] (udplogviewer) This package is up to date.
[INFO] (udpp2p) This package is up to date.
[INFO] (udprecv) This package is up to date.
[INFO] (udprelay) This package is up to date.
[INFO] (udr) This package is up to date.
[INFO] (uds) This package is up to date.
[INFO] (udserver) This package is up to date.
[INFO] (udsi) This package is up to date.
[INFO] (udsnd-distributions) Data has been updated for this package.
[INFO] (udsoncan) Data has been updated for this package.
[INFO] (udsxmlrpc) Data has been updated for this package.
[INFO] (udt) Data has been updated for this package.
[INFO] (udt4py) This package is up to date.
[INFO] (udt4twisted) This package is up to date.
[INFO] (udtherapy) This package is up to date.
[INFO] (udunitspy) This package is up to date.
[INFO] (ue-schedule) Data has been updated for this package.
[INFO] (ue4-ci-helpers) Data has been updated for this package.
[INFO] (ue4-docker) Data has been updated for this package.
[INFO] (ue4cli) Data has been updated for this package.
[INFO] (uea-ucr-datasets) Data has been updated for this package.
[INFO] (ueagle) Data has been updated for this package.
[INFO] (ueberzug) Data has been updated for this package.
[ERROR] (ueberzug-nosimd) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (uec) This package is up to date.
[INFO] (uedge) Data has been updated for this package.
[INFO] (ueditor) This package is up to date.
[INFO] (ueditor-nimbus) This package is up to date.
[INFO] (ueditor4tornado) This package is up to date.
[INFO] (uefi-firmware) This package is up to date.
[INFO] (uek-abc) This package is up to date.
[INFO] (uek-ex-pkg) This package is up to date.
[INFO] (uek-light1111) This package is up to date.
[INFO] (uek-sayhello) This package is up to date.
[INFO] (uek-test-one) This package is up to date.
[INFO] (uek-wyc-one) This package is up to date.
[INFO] (uengine) Data has been updated for this package.
[INFO] (uesgraphs) Data has been updated for this package.
[INFO] (uestc) This package is up to date.
[INFO] (uestcct) This package is up to date.
[INFO] (uetla) This package is up to date.
[INFO] (ufal-morphodita) This package is up to date.
[INFO] (ufal-nametag) This package is up to date.
[INFO] (ufal-parsito) This package is up to date.
[INFO] (ufal-udpipe) Data has been updated for this package.
[INFO] (ufal-udpipe-temp) Data has been updated for this package.
[ERROR] (ufc) Could not extract data from this package. See below for details.
"https://bitbucket.org/fenics-project/ufc/downloads/ufc-2.3.0.tar.gz" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (ufcstats) This package is up to date.
[INFO] (uff-widget) Data has been updated for this package.
[INFO] (ufile) Data has been updated for this package.
[INFO] (ufinance) This package is up to date.
[INFO] (ufit) This package is up to date.
[ERROR] (ufji) Could not extract data from this package. See below for details.

[INFO] (ufl) This package is up to date.
[ERROR] (uflacs) This package does not have downloadable releases.
[INFO] (uflash) Data has been updated for this package.
[INFO] (ufload) Data has been updated for this package.
[INFO] (ufma-scrapper) Data has been updated for this package.
[INFO] (ufma-scrapperpy) Data has been updated for this package.
[INFO] (ufo) Data has been updated for this package.
[INFO] (ufo-extractor) Data has been updated for this package.
[INFO] (ufo-filter) This package is up to date.
[INFO] (ufo2ft) Data has been updated for this package.
[INFO] (ufo2otf) This package is up to date.
[INFO] (ufobit) This package is up to date.
[INFO] (ufodiff) This package is up to date.
[INFO] (ufolib) This package is up to date.
[INFO] (ufolib2) Data has been updated for this package.
[INFO] (ufolint) Data has been updated for this package.
[INFO] (ufonormalizer) This package is up to date.
[INFO] (ufoprocessor) Data has been updated for this package.
[INFO] (uforge-marketplace-python-sdk) This package is up to date.
[INFO] (uforge-python-sdk) This package is up to date.
[INFO] (uforge-python-sdk-nightly) This package is up to date.
[INFO] (uforgecli) This package is up to date.
[INFO] (uforgecli-nightly) This package is up to date.
[INFO] (ufork) This package is up to date.
[INFO] (ufp) This package is up to date.
[INFO] (ufs-sdk) This package is up to date.
[INFO] (ufs-tools) This package is up to date.
[INFO] (uftlib) This package is up to date.
[INFO] (ufx) This package is up to date.
[ERROR] (ug-dst) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (uga) Data has been updated for this package.
[INFO] (ugali) This package is up to date.
[INFO] (ugc-sentiment) This package is up to date.
[INFO] (ugd) Data has been updated for this package.
[INFO] (uge-drmaa2) Data has been updated for this package.
[INFO] (uge-pycl) Data has been updated for this package.
[INFO] (ugentbiblio) This package is up to date.
[INFO] (ugetcli) This package is up to date.
[INFO] (ugh) This package is up to date.
[INFO] (ugid) Data has been updated for this package.
[INFO] (uglipy) This package is up to date.
[INFO] (uglipyjs) This package is up to date.
[INFO] (ugly) This package is up to date.
[INFO] (ugly-code) Data has been updated for this package.
[INFO] (ugly-sql) Data has been updated for this package.
[INFO] (ugmark1) This package is up to date.
[INFO] (ugo) This package is up to date.
[INFO] (ugoira) Data has been updated for this package.
[INFO] (ugravatar) This package is up to date.
[INFO] (ugtm) This package is up to date.
[ERROR] (uguese) This package does not have downloadable releases.
[INFO] (uguu) This package is up to date.
[INFO] (uh) This package is up to date.
[INFO] (uh-opcunix-jgirdwood) This package is up to date.
[INFO] (uh-pyopcn3) Data has been updated for this package.
[INFO] (uhammer) This package is up to date.
[INFO] (uharfbuzz) This package is up to date.
[INFO] (uhashring) This package is up to date.
[INFO] (uhb) This package is up to date.
[INFO] (uhcx) This package is up to date.
[ERROR] (uhdl) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (uhdvna) This package does not have downloadable releases.
[INFO] (uhelpers) Data has been updated for this package.
[INFO] (uheprng) This package is up to date.
[INFO] (uhf-rfid-reader-sdk) Data has been updated for this package.
[ERROR] (uhh-cs294) This package does not have downloadable releases.
[ERROR] (uhhcs294) This package does not have downloadable releases.
[INFO] (uhid-freebsd) Data has been updated for this package.
[INFO] (uhome) Data has been updated for this package.
[INFO] (uhttplib) This package is up to date.
[INFO] (uhu) This package is up to date.
[INFO] (ui) This package is up to date.
[INFO] (ui-navigate) This package is up to date.
[INFO] (ui-to-py) This package is up to date.
[INFO] (ui-translator) This package is up to date.
[ERROR] (ui57) This package does not have downloadable releases.
[INFO] (uiautomation) This package is up to date.
[INFO] (uiautomator) This package is up to date.
[INFO] (uiautomator2) Data has been updated for this package.
[INFO] (uiautomatorplug) This package is up to date.
[INFO] (uib-experiments) Data has been updated for this package.
[INFO] (uib-vfeatures) Data has been updated for this package.
[INFO] (uic920) This package is up to date.
[INFO] (uidgenerator-utils) This package is up to date.
[INFO] (uielem) This package is up to date.
[INFO] (uifunc) This package is up to date.
[INFO] (uikit) This package is up to date.
[INFO] (uimap) This package is up to date.
[INFO] (uinames) This package is up to date.
[INFO] (uinfo) This package is up to date.
[INFO] (uint) Data has been updated for this package.
[INFO] (uiotedge-driver-link-sdk) Data has been updated for this package.
[INFO] (uip) This package is up to date.
[INFO] (uip-scrape) This package is up to date.
[INFO] (uipath) This package is up to date.
[INFO] (uipath-cloud) Data has been updated for this package.
[INFO] (uipath-enhanced-reframework-generator) This package is up to date.
[INFO] (uipath-scaffold) This package is up to date.
[INFO] (uipath-scaffold-generator) This package is up to date.
[INFO] (uipath-tools) Data has been updated for this package.
[INFO] (uipcalc) This package is up to date.
[INFO] (uiperf3) This package is up to date.
[INFO] (uiplug) Data has been updated for this package.
[INFO] (uiro) This package is up to date.
[ERROR] (uis-dsm) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (uiside) This package is up to date.
[INFO] (uisoup) This package is up to date.
[INFO] (uisrnn) Data has been updated for this package.
[INFO] (uitable) Data has been updated for this package.
[INFO] (uitdatabank) This package is up to date.
[INFO] (uitest) Data has been updated for this package.
[INFO] (uitestcore) Data has been updated for this package.
[INFO] (uitestframework) This package is up to date.
[ERROR] (uitestframework-joshuacruzc) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (uitestool) This package is up to date.
[INFO] (uitranslator) This package is up to date.
[INFO] (uiuc-mas) This package is up to date.
[INFO] (uiucapi) This package is up to date.
[INFO] (uiutil) Data has been updated for this package.
[INFO] (uiza) This package is up to date.
[INFO] (uji) Data has been updated for this package.
[INFO] (uji-ship) This package is up to date.
[INFO] (ujoscheme) Data has been updated for this package.
[INFO] (ujotypes) Data has been updated for this package.
[INFO] (ujs-jsonsyntax) This package is up to date.
[INFO] (ujs-jsonvalidate) This package is up to date.
[INFO] (ujs-safefile) This package is up to date.
[INFO] (ujson) This package is up to date.
[INFO] (ujson-bedframe) This package is up to date.
[INFO] (ujson-delta) This package is up to date.
[INFO] (ujson-drf) This package is up to date.
[INFO] (ujson-ia) This package is up to date.
[INFO] (ujson-segfault) This package is up to date.
[INFO] (ujson-x) This package is up to date.
[INFO] (ujson-x-legacy) This package is up to date.
[INFO] (ujsondb) This package is up to date.
[INFO] (ujsongp) This package is up to date.
[INFO] (ujsonpath) This package is up to date.
[ERROR] (uk) This package does not have downloadable releases.
[INFO] (uk-boards) Data has been updated for this package.
[INFO] (uk-election-ids) Data has been updated for this package.
[INFO] (uk-geo-utils) Data has been updated for this package.
[INFO] (uk-postcode-utils) This package is up to date.
[INFO] (uk-postcode-validator) This package is up to date.
[INFO] (uk-postcodes) This package is up to date.
[INFO] (ukbb-parser) Data has been updated for this package.
[INFO] (ukbc) Data has been updated for this package.
[INFO] (ukbparse) This package is up to date.
[INFO] (ukcensusapi) This package is up to date.
[INFO] (ukchurn-classification-model) Data has been updated for this package.
[INFO] (ukds) Data has been updated for this package.
[INFO] (ukedown) Data has been updated for this package.
[INFO] (ukervi) Data has been updated for this package.
[INFO] (ukflib) This package is up to date.
[INFO] (ukgov-treasury-cra) This package is up to date.
[INFO] (ukmdb-amqp) This package is up to date.
[INFO] (ukmdb-audit) This package is up to date.
[INFO] (ukmdb-checkmk) This package is up to date.
[INFO] (ukmdb-cli) This package is up to date.
[INFO] (ukmdb-db) This package is up to date.
[INFO] (ukmdb-graph) This package is up to date.
[INFO] (ukmdb-itop) This package is up to date.
[INFO] (ukmdb-settings) This package is up to date.
[INFO] (ukmdb-uuid) This package is up to date.
[INFO] (ukmdb-worker) This package is up to date.
[INFO] (ukmodulus) This package is up to date.
[INFO] (ukonline-pyds) This package is up to date.
[INFO] (ukparliament) This package is up to date.
[INFO] (ukpc) This package is up to date.
[INFO] (ukpcode) This package is up to date.
[INFO] (ukpf) Data has been updated for this package.
[INFO] (ukpocopy) This package is up to date.
[INFO] (ukpol-cli) This package is up to date.
[INFO] (ukpopulation) This package is up to date.
[INFO] (ukpostalcode) This package is up to date.
[INFO] (ukpostcode) This package is up to date.
[INFO] (ukpostcodeparser) This package is up to date.
[INFO] (ukpostcodevalidator) This package is up to date.
[INFO] (ukrdict) Data has been updated for this package.
[INFO] (ukt) Data has been updated for this package.
[INFO] (ukuxhumana) This package is up to date.
[INFO] (ukv1-toolbox) Data has been updated for this package.
[ERROR] (ukvsclient) This package does not have downloadable releases.
[INFO] (ukyvub0ffj) This package is up to date.
[INFO] (ulakbus) This package is up to date.
[INFO] (ulam-spiral) This package is up to date.
[INFO] (ulangel) Data has been updated for this package.
[INFO] (ulars) Data has been updated for this package.
[INFO] (ulaval-notify) This package is up to date.
[INFO] (ulawwave) This package is up to date.
[INFO] (uldaq) Data has been updated for this package.
[INFO] (uliacceleration) This package is up to date.
[INFO] (ulib) This package is up to date.
[INFO] (ulid) This package is up to date.
[INFO] (ulid-py) Data has been updated for this package.
[INFO] (ulid2) This package is up to date.
[INFO] (uliengineering) Data has been updated for this package.
[INFO] (ulif-loghandlers) This package is up to date.
[INFO] (ulif-openoffice) This package is up to date.
[INFO] (ulif-plone-testsetup) This package is up to date.
[INFO] (ulif-pynotify) This package is up to date.
[INFO] (ulif-rest) This package is up to date.
[INFO] (ulint) This package is up to date.
[INFO] (ulint-pep8) This package is up to date.
[ERROR] (ulipad) Could not extract data from this package. See below for details.
"http://ulipad.googlecode.com/files/ulipad.4.1.zip" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (ulit) This package is up to date.
[INFO] (uliweb) This package is up to date.
[INFO] (uliweb-alembic) This package is up to date.
[INFO] (uliweb-apijson) Data has been updated for this package.
[INFO] (uliweb-apps) This package is up to date.
[INFO] (uliweb-comapps) Data has been updated for this package.
[INFO] (uliweb-comui) Data has been updated for this package.
[INFO] (uliweb-layout) This package is up to date.
[INFO] (uliweb-menu) This package is up to date.
[INFO] (uliweb-ui) This package is up to date.
[INFO] (uliweb3) This package is up to date.
[INFO] (ulka) This package is up to date.
[INFO] (ullvm) Data has been updated for this package.
[INFO] (ullvm-c) Data has been updated for this package.
[INFO] (ulmo) This package is up to date.
[INFO] (ulo) This package is up to date.
[INFO] (ulog) This package is up to date.
[INFO] (ulog-tools) This package is up to date.
[INFO] (ulogger) This package is up to date.
[INFO] (ulozto-downloader) Data has been updated for this package.
[INFO] (ulp) This package is up to date.
[INFO] (ulstools) This package is up to date.
[INFO] (ult) This package is up to date.
[INFO] (ultan) This package is up to date.
[INFO] (ultimaker-printer-api) Data has been updated for this package.
[INFO] (ultimapy) Data has been updated for this package.
[INFO] (ultimate) This package is up to date.
[INFO] (ultimate-hosts-blacklist-central-repo-updater) Data has been updated for this package.
[INFO] (ultimate-hosts-blacklist-comparison) Data has been updated for this package.
[INFO] (ultimate-hosts-blacklist-helpers) Data has been updated for this package.
[INFO] (ultimate-hosts-blacklist-input-repo-updater) Data has been updated for this package.
[INFO] (ultimate-hosts-blacklist-the-whitelist) This package is up to date.
[INFO] (ultimate-hosts-blacklist-whitelist) Data has been updated for this package.
[INFO] (ultimate-sitemap-parser) Data has been updated for this package.
[ERROR] (ultimate-smash-friends) This package does not have downloadable releases.
[INFO] (ultimate-ttt) This package is up to date.
[ERROR] (ultimate-webshots-converter-for-kde) Could not extract data from this package. See below for details.
".php" extension not supported.
[INFO] (ultimatelabeling) This package is up to date.
[INFO] (ultimatepkg2) This package is up to date.
[INFO] (ultimatum) This package is up to date.
[INFO] (ultimux) Data has been updated for this package.
[INFO] (ultra-config) This package is up to date.
[INFO] (ultra-config-kms-cli) This package is up to date.
[INFO] (ultra-random-uuid) This package is up to date.
[INFO] (ultra-rest-client) This package is up to date.
[ERROR] (ultra10) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (ultrachronic) This package is up to date.
[INFO] (ultraconfig) This package is up to date.
[INFO] (ultracrawler) This package is up to date.
[INFO] (ultracup-nester) This package is up to date.
[INFO] (ultrafastultrafast) This package is up to date.
[ERROR] (ultrahash) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (ultraheatmap) Data has been updated for this package.
[INFO] (ultraify) This package is up to date.
[INFO] (ultralite) This package is up to date.
[INFO] (ultramarine) This package is up to date.
[INFO] (ultranest) Data has been updated for this package.
[INFO] (ultrasequence) This package is up to date.
[INFO] (ultrasnip) Data has been updated for this package.
[ERROR] (ultrasound) This package does not have downloadable releases.
[INFO] (ultrastar-pitch) Data has been updated for this package.
[INFO] (ultratransmission) This package is up to date.
[INFO] (ultrello) This package is up to date.
[INFO] (ultron) This package is up to date.
[INFO] (ultru-cli) Data has been updated for this package.
[INFO] (ultru-query) Data has been updated for this package.
[INFO] (uluplot) This package is up to date.
[INFO] (ulutil) This package is up to date.
[INFO] (ulvl) This package is up to date.
[INFO] (ulysses) This package is up to date.
[INFO] (um) Data has been updated for this package.
[INFO] (um7) This package is up to date.
[INFO] (umadevi-nester) This package is up to date.
[INFO] (umakaviewer) Data has been updated for this package.
[INFO] (umakit) This package is up to date.
[INFO] (umalqurra) This package is up to date.
[INFO] (umami) Data has been updated for this package.
[INFO] (umansysprop) This package is up to date.
[INFO] (umap) This package is up to date.
[INFO] (umap-learn) Data has been updated for this package.
[INFO] (umap-learn-modified) Data has been updated for this package.
[INFO] (umap-project) This package is up to date.
[INFO] (umapi-client) Data has been updated for this package.
[INFO] (umat) This package is up to date.
[INFO] (umb) This package is up to date.
[INFO] (umbi) This package is up to date.
[INFO] (umbr-api) This package is up to date.
[INFO] (umbra) This package is up to date.
[INFO] (umbral) Data has been updated for this package.
[ERROR] (umbrella) This package does not have downloadable releases.
[INFO] (umbrellaintegrate) This package is up to date.
[ERROR] (umclient) This package does not have downloadable releases.
[INFO] (umdh) This package is up to date.
[INFO] (umdriver) Data has been updated for this package.
[INFO] (umemcache) This package is up to date.
[INFO] (umeng-push) This package is up to date.
[INFO] (umfactory) This package is up to date.
[INFO] (umfpayservice) This package is up to date.
[INFO] (umi) This package is up to date.
[INFO] (umi-tools) Data has been updated for this package.
[INFO] (umich-projkit) This package is up to date.
[INFO] (umihico) This package is up to date.
[INFO] (umilandez) This package is up to date.
[INFO] (umimbutil) This package is up to date.
[INFO] (umiread) This package is up to date.
[INFO] (umis) This package is up to date.
[ERROR] (umit) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "http://www.umitproject.org"
[INFO] (umitools) This package is up to date.
[INFO] (uml) This package is up to date.
[INFO] (uml2orm) This package is up to date.
[INFO] (umls-auth) This package is up to date.
[INFO] (umls-request-manager) This package is up to date.
[INFO] (ummalqura) This package is up to date.
[INFO] (ummodulomaluco344234) This package is up to date.
[INFO] (umnester) This package is up to date.
[ERROR] (umnomequalquer) This package does not have downloadable releases.
[INFO] (umobj) Data has been updated for this package.
[INFO] (umock) Data has been updated for this package.
[INFO] (umodbus) Data has been updated for this package.
[INFO] (umodbus-extended) Data has been updated for this package.
[INFO] (umodules) This package is up to date.
[ERROR] (umol) This package does not have downloadable releases.
[INFO] (umongo) Data has been updated for this package.
[INFO] (umopener) This package is up to date.
[INFO] (umorpheme) This package is up to date.
[INFO] (ump) This package is up to date.
[INFO] (umpire) Data has been updated for this package.
[INFO] (umplot) This package is up to date.
[INFO] (umpy) This package is up to date.
[INFO] (ums-doc-swag) This package is up to date.
[INFO] (ums-doc-swagger) This package is up to date.
[INFO] (umsgpack) This package is up to date.
[INFO] (umsgpackpython) This package is up to date.
[INFO] (umtools) This package is up to date.
[INFO] (umwelt) Data has been updated for this package.
[INFO] (umysql) This package is up to date.
[INFO] (umysql-2018) This package is up to date.
[INFO] (umysql3) This package is up to date.
[INFO] (umysqldb) This package is up to date.
[INFO] (un-iife-ize) This package is up to date.
[ERROR] (un-nester) This package does not have downloadable releases.
[INFO] (un-treaties) This package is up to date.
[INFO] (un-xtab) Data has been updated for this package.
[INFO] (una-django-cassandra-engine) This package is up to date.
[INFO] (unach-photo) This package is up to date.
[INFO] (unach-photo-server) This package is up to date.
[INFO] (unagi) Data has been updated for this package.
[ERROR] (unagi-py) Could not extract data from this package. See below for details.
".html" extension not supported.
[INFO] (unakite) Data has been updated for this package.
[ERROR] (unalog-python) This package does not have downloadable releases.
[INFO] (uname2) Data has been updated for this package.
[INFO] (unanimous) Data has been updated for this package.
[INFO] (unapid) This package is up to date.
[INFO] (unary-coding) Data has been updated for this package.
[INFO] (unassigner) This package is up to date.
[INFO] (unasync) Data has been updated for this package.
[INFO] (unbabel-py) This package is up to date.
[INFO] (unbounce-python-api) Data has been updated for this package.
[INFO] (unbound-ec2) This package is up to date.
[INFO] (unboxftpd) This package is up to date.
[INFO] (unbroken-pyobjc) This package is up to date.
[INFO] (unbuffered-input) This package is up to date.
[INFO] (uncalled) This package is up to date.
[INFO] (uncap-pkg-ergrim) Data has been updated for this package.
[INFO] (uncatchable-exception) This package is up to date.
[INFO] (uncertain-panda) This package is up to date.
[INFO] (uncertainpy) This package is up to date.
[INFO] (uncertainties) Data has been updated for this package.
[INFO] (uncertainty) This package is up to date.
[INFO] (uncertainty-calibration) Data has been updated for this package.
[INFO] (uncertainty-wrapper) This package is up to date.
[INFO] (uncertaintywrapper) This package is up to date.
[INFO] (unchain) This package is up to date.
[INFO] (unchaind) This package is up to date.
[INFO] (unchaindjango) This package is up to date.
[ERROR] (unchained) This package does not have downloadable releases.
[INFO] (uncle-nester) This package is up to date.
[INFO] (unclebash) This package is up to date.
[INFO] (unclebob) This package is up to date.
[INFO] (unclectowelstuff) This package is up to date.
[INFO] (uncleengineer) This package is up to date.
[INFO] (unclegabe) This package is up to date.
[INFO] (uncommitted) This package is up to date.
[INFO] (uncompyle) This package is up to date.
[INFO] (uncompyle2) This package is up to date.
[INFO] (uncompyle6) Data has been updated for this package.
[INFO] (uncover-ml) Data has been updated for this package.
[INFO] (uncrumpled-async-gui) This package is up to date.
[INFO] (uncrumpled-kivy) This package is up to date.
[INFO] (uncrumpled-kivygui) This package is up to date.
[INFO] (uncrumpled-xpybutil) This package is up to date.
[INFO] (uncrustify-objc) Data has been updated for this package.
[INFO] (uncsom-recipe-ploneupdater) This package is up to date.
[INFO] (uncurl) This package is up to date.
[INFO] (uncurl-seq) This package is up to date.
[INFO] (und-microservice) This package is up to date.
[INFO] (undaqtools) This package is up to date.
[INFO] (undead) This package is up to date.
[INFO] (undebt) This package is up to date.
[INFO] (undecorate) This package is up to date.
[INFO] (undecorated) This package is up to date.
[INFO] (undefined) Data has been updated for this package.
[INFO] (underarmour) This package is up to date.
[INFO] (underground) Data has been updated for this package.
[INFO] (underline-turntable) This package is up to date.
[INFO] (underpy) This package is up to date.
[INFO] (underscode) This package is up to date.
[INFO] (underscore) This package is up to date.
[INFO] (underscore-py) This package is up to date.
[INFO] (underscorepy) This package is up to date.
[ERROR] (underscorex) Could not extract data from this package. See below for details.
Unsupported package directory structure.
[INFO] (understat) Data has been updated for this package.
[INFO] (understate) This package is up to date.
[INFO] (understreck) Data has been updated for this package.
[INFO] (underthesea) Data has been updated for this package.
[INFO] (undertime) Data has been updated for this package.
[INFO] (underverse) This package is up to date.
[INFO] (undervolt) Data has been updated for this package.
[INFO] (underwater-adventure) Data has been updated for this package.
[INFO] (underwear) This package is up to date.
[INFO] (underworlds) This package is up to date.
[INFO] (undict) This package is up to date.
[INFO] (undictify) Data has been updated for this package.
[INFO] (undname) This package is up to date.
[ERROR] (undo) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "http://bitbucket.org/aquavitae/undo/downloads"
[INFO] (undoable) This package is up to date.
[INFO] (undoable-transaction) This package is up to date.
[INFO] (undocker) This package is up to date.
[INFO] (undopy) This package is up to date.
[INFO] (undoredo) This package is up to date.
[INFO] (undrp) This package is up to date.
[INFO] (undupe) Data has been updated for this package.
[INFO] (unebus) This package is up to date.
[INFO] (unenchhash) This package is up to date.
[INFO] (unet) Data has been updated for this package.
[INFO] (unete) This package is up to date.
[INFO] (unetpy) Data has been updated for this package.
[INFO] (unf) This package is up to date.
[INFO] (unfairseq) This package is up to date.
[INFO] (unfinnigan) This package is up to date.
[INFO] (unflatten) This package is up to date.
[INFO] (unfluff) This package is up to date.
[INFO] (unfold-protein) This package is up to date.
[INFO] (unfollower) This package is up to date.
[INFO] (unfromm) This package is up to date.
[INFO] (unfurl) Data has been updated for this package.
[INFO] (ungleich-cli) This package is up to date.
[INFO] (ungog) This package is up to date.
[INFO] (unha) This package is up to date.
[INFO] (unhinged) Data has been updated for this package.
[INFO] (unholster-django-lookup) This package is up to date.
[INFO] (unholster-milieu) This package is up to date.
[INFO] (uni) This package is up to date.
[INFO] (uni-slugify) This package is up to date.
[INFO] (uni2ascii-janin) This package is up to date.
[INFO] (uni2esky) This package is up to date.
[INFO] (uniauth) This package is up to date.
[INFO] (unibert) Data has been updated for this package.
[INFO] (uniblock) Data has been updated for this package.
[INFO] (uniboard-raspberrypi) This package is up to date.
[INFO] (uniboost) Data has been updated for this package.
[ERROR] (uniborg) Could not extract data from this package. See below for details.
Unsupported package directory structure.
[INFO] (unibot) Data has been updated for this package.
[INFO] (unicampauth) This package is up to date.
[ERROR] (unicampi) This package does not have downloadable releases.
[INFO] (unicards) This package is up to date.
[INFO] (unicategories) This package is up to date.
[INFO] (unice-mosaique) This package is up to date.
[INFO] (unice-portlet-boutique) This package is up to date.
[INFO] (unice-portlet-coordonnees) This package is up to date.
[INFO] (unice-portlet-evenementiels) This package is up to date.
[INFO] (unice-portlet-flickr) This package is up to date.
[INFO] (unice-portlet-focus) This package is up to date.
[INFO] (unice-portlet-imagelegendee) This package is up to date.
[INFO] (unice-portlet-lettre) This package is up to date.
[INFO] (unice-portlet-mosaique) This package is up to date.
[INFO] (unice-portlet-mot) This package is up to date.
[INFO] (unice-portlet-profil) This package is up to date.
[INFO] (unice-portlet-slider) This package is up to date.
[INFO] (unice-portlet-stories) This package is up to date.
[INFO] (unice-portlet-telechargement) This package is up to date.
[INFO] (unice-portlet-vimeo) This package is up to date.
[INFO] (unicef-attachments) Data has been updated for this package.
[INFO] (unicef-djangolib) This package is up to date.
[INFO] (unicef-djangosaml2) This package is up to date.
[INFO] (unicef-locations) Data has been updated for this package.
[INFO] (unicef-notification) This package is up to date.
[INFO] (unicef-rest-export) This package is up to date.
[INFO] (unicef-restlib) Data has been updated for this package.
[INFO] (unicef-security) Data has been updated for this package.
[INFO] (unicef-snapshot) This package is up to date.
[INFO] (unicef-vision) Data has been updated for this package.
[INFO] (unicity) Data has been updated for this package.
[INFO] (unicmobile-common) This package is up to date.
[ERROR] (unico) This package does not have downloadable releases.
[INFO] (unicode) This package is up to date.
[INFO] (unicode-babel) Data has been updated for this package.
[INFO] (unicode-charnames) Data has been updated for this package.
[INFO] (unicode-ids) This package is up to date.
[INFO] (unicode-mayo) Data has been updated for this package.
[INFO] (unicode-nazi) This package is up to date.
[ERROR] (unicode-please) This package does not have downloadable releases.
[INFO] (unicode-slugify) This package is up to date.
[INFO] (unicode-slugify-latin) This package is up to date.
[INFO] (unicode-string-literal) This package is up to date.
[INFO] (unicode-tex) This package is up to date.
[INFO] (unicode-tr) This package is up to date.
[INFO] (unicode2utf8) This package is up to date.
[INFO] (unicodeblock) Data has been updated for this package.
[INFO] (unicodeblocks) This package is up to date.
[ERROR] (unicodeblocktokenizer) This package does not have downloadable releases.
[INFO] (unicodecsv) This package is up to date.
[INFO] (unicodedata2) Data has been updated for this package.
[INFO] (unicodedataplus) This package is up to date.
[INFO] (unicodemanager) This package is up to date.
[INFO] (unicodemoticon) This package is up to date.
[INFO] (unicodescript) This package is up to date.
[INFO] (unicodeset) This package is up to date.
[INFO] (unicodeslugify) This package is up to date.
[INFO] (unicodeutil) Data has been updated for this package.
[ERROR] (unicoding) This package does not have downloadable releases.
[INFO] (unicoin) Data has been updated for this package.
[INFO] (unicon) Data has been updated for this package.
[INFO] (unicon-plugins) Data has been updated for this package.
[INFO] (uniconfig) This package is up to date.
[INFO] (uniconnect-python-client) Data has been updated for this package.
[INFO] (unicontent) This package is up to date.
[INFO] (unicore-ask) This package is up to date.
[INFO] (unicore-cms) This package is up to date.
[INFO] (unicore-cms-django) This package is up to date.
[INFO] (unicore-comments-client) This package is up to date.
[INFO] (unicore-content) This package is up to date.
[INFO] (unicore-distribute) This package is up to date.
[INFO] (unicore-gitmodels) This package is up to date.
[INFO] (unicore-google) This package is up to date.
[INFO] (unicore-hub-client) This package is up to date.
[INFO] (unicore-languages) This package is up to date.
[INFO] (unicore-webhooks) This package is up to date.
[INFO] (unicorm) This package is up to date.
[INFO] (unicorn) This package is up to date.
[INFO] (unicorn-banner) This package is up to date.
[INFO] (unicorn-binance-websocket-api) Data has been updated for this package.
[ERROR] (unicorn-binance-websocket-api-development) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (unicorn-ca-herd) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (unicorn-engine) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "http://unicorn-engine.org"
[INFO] (unicorn-fy) Data has been updated for this package.
[INFO] (unicorn-hat-sim) This package is up to date.
[INFO] (unicorn-pwrs) This package is up to date.
[INFO] (unicorn-tracer) This package is up to date.
[INFO] (unicorn-unipacker) Data has been updated for this package.
[INFO] (unicornclient) Data has been updated for this package.
[INFO] (unicorner) Data has been updated for this package.
[INFO] (unicornhat) This package is up to date.
[INFO] (unicornhathd) This package is up to date.
[INFO] (unicornherder) This package is up to date.
[INFO] (unicover) This package is up to date.
[INFO] (unicsv) This package is up to date.
[INFO] (unicum) Data has been updated for this package.
[ERROR] (unicurses) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "https://sourceforge.net/projects/pyunicurses/"
[ERROR] (unicurses-for-python) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "https://sourceforge.net/projects/pyunicurses/"
[INFO] (unidbm) This package is up to date.
[INFO] (unide-python) This package is up to date.
[INFO] (unidecode) This package is up to date.
[INFO] (unidic) Data has been updated for this package.
[INFO] (unidic2ud) Data has been updated for this package.
[INFO] (unidiff) This package is up to date.
[INFO] (unidip) This package is up to date.
[INFO] (unidist) This package is up to date.
[INFO] (unidown) This package is up to date.
[INFO] (unidown-mr-de) This package is up to date.
[INFO] (unidump) This package is up to date.
[INFO] (uniexpect) This package is up to date.
[INFO] (unifi) This package is up to date.
[INFO] (unifi-api) This package is up to date.
[INFO] (unifi-client) This package is up to date.
[INFO] (unifi-python-api) Data has been updated for this package.
[INFO] (unifi-sh) This package is up to date.
[INFO] (unifi-video) Data has been updated for this package.
[INFO] (unification) This package is up to date.
[INFO] (unificontrol) Data has been updated for this package.
[INFO] (unified) Data has been updated for this package.
[INFO] (unified-api-pkg) Data has been updated for this package.
[INFO] (unified-map) This package is up to date.
[INFO] (unified-plotting) This package is up to date.
[INFO] (unified-range) Data has been updated for this package.
[INFO] (unified2) This package is up to date.
[INFO] (unifiedlog) This package is up to date.
[INFO] (unifile) Data has been updated for this package.
[INFO] (unifiled) Data has been updated for this package.
[INFO] (unifipy) Data has been updated for this package.
[INFO] (uniflash) This package is up to date.
[ERROR] (uniform) This package does not have downloadable releases.
[INFO] (unifrac) This package is up to date.
[INFO] (unify) Data has been updated for this package.
[INFO] (unihan-etl) Data has been updated for this package.
[INFO] (unihan-tabular) This package is up to date.
[INFO] (unihandecode) This package is up to date.
[INFO] (unijson) This package is up to date.
[INFO] (unikold-connector) This package is up to date.
[INFO] (unilint) This package is up to date.
[INFO] (unilog) This package is up to date.
[INFO] (unimate) This package is up to date.
[INFO] (unimatrix) Data has been updated for this package.
[INFO] (unimatrix-ext-django) Data has been updated for this package.
[INFO] (unimatrix-ext-one) Data has been updated for this package.
[INFO] (unimatrix-ext-vault) Data has been updated for this package.
[INFO] (unimi-unsubscribe) This package is up to date.
[INFO] (unimod) This package is up to date.
[INFO] (unimonapi) Data has been updated for this package.
[INFO] (unimorph) Data has been updated for this package.
[INFO] (unimport) Data has been updated for this package.
[INFO] (unimr-compositeindex) This package is up to date.
[INFO] (unimr-memcachedlock) This package is up to date.
[INFO] (unimr-red5-protectedvod) This package is up to date.
[INFO] (uninhibited) This package is up to date.
[INFO] (uninstall-app) This package is up to date.
[INFO] (uninstallable) This package is up to date.
[INFO] (union) This package is up to date.
[INFO] (union-find) This package is up to date.
[INFO] (unionchat) This package is up to date.
[INFO] (unioncom) Data has been updated for this package.
[INFO] (unionfind) This package is up to date.
[INFO] (unionpay) Data has been updated for this package.
[INFO] (unionservice) Data has been updated for this package.
[INFO] (uniontypes) This package is up to date.
[INFO] (uniopen) This package is up to date.
[INFO] (uniout) This package is up to date.
[INFO] (unipacker) Data has been updated for this package.
[INFO] (unipad) This package is up to date.
[INFO] (unipag) This package is up to date.
[INFO] (unipath) This package is up to date.
[INFO] (unipdgest-portlet-navigation) This package is up to date.
[INFO] (uniphy) This package is up to date.
[INFO] (uniplaces-aws-scheduler) This package is up to date.
[INFO] (uniplate) This package is up to date.
[INFO] (uniprop) This package is up to date.
[INFO] (uniprot) This package is up to date.
[INFO] (uniprot-mapper) This package is up to date.
[INFO] (uniprot-tools) This package is up to date.
[INFO] (uniprotmapper) This package is up to date.
[INFO] (unipy) This package is up to date.
[INFO] (unipy-db) This package is up to date.
[INFO] (unipy-logger) This package is up to date.
[INFO] (uniq) This package is up to date.
[INFO] (uniqid) This package is up to date.
[INFO] (uniqtoken) This package is up to date.
[INFO] (unique) This package is up to date.
[INFO] (unique-id) This package is up to date.
[INFO] (unique-id-gen) This package is up to date.
[INFO] (unique-sam) This package is up to date.
[INFO] (uniquepath) This package is up to date.
[INFO] (uniquepwd) This package is up to date.
[INFO] (uniquewords) This package is up to date.
[INFO] (uniquid) This package is up to date.
[INFO] (uniquify) This package is up to date.
[INFO] (unireedsolomon) This package is up to date.
[INFO] (unirest) This package is up to date.
[INFO] (unirio-api) This package is up to date.
[INFO] (unirio-sie) This package is up to date.
[INFO] (unirw) This package is up to date.
[INFO] (unisc) This package is up to date.
[INFO] (unischeduler) Data has been updated for this package.
[INFO] (uniscripts) This package is up to date.
[INFO] (uniseg) This package is up to date.
[INFO] (unishark) This package is up to date.
[ERROR] (unison) This package does not have downloadable releases.
[INFO] (unisonctl) This package is up to date.
[INFO] (unisos) This package is up to date.
[INFO] (unisos-common) This package is up to date.
[INFO] (unisos-cryptkeyring) Data has been updated for this package.
[INFO] (unisos-githubapi) This package is up to date.
[INFO] (unisos-icm) This package is up to date.
[INFO] (unisos-icmexample) This package is up to date.
[INFO] (unisos-marme) This package is up to date.
[INFO] (unisos-mmwsicm) This package is up to date.
[INFO] (unisos-symcrypt) Data has been updated for this package.
[INFO] (unisos-ucf) This package is up to date.
[INFO] (unisos-utils) This package is up to date.
[INFO] (unisos-wsinvokericm) This package is up to date.
[INFO] (unisos-x822msg) This package is up to date.
[INFO] (unisquid) This package is up to date.
[INFO] (uniswap-python) Data has been updated for this package.
[INFO] (unisync) Data has been updated for this package.
[INFO] (unit) This package is up to date.
[INFO] (unit-conversion) This package is up to date.
[INFO] (unit-converter) This package is up to date.
[INFO] (unit-parser) This package is up to date.
[INFO] (unit-py) This package is up to date.
[INFO] (unit-system) Data has been updated for this package.
[INFO] (unit-systems) Data has been updated for this package.
[INFO] (unitable) This package is up to date.
[INFO] (unitconvert) This package is up to date.
[INFO] (unitdoc) Data has been updated for this package.
[ERROR] (unitdox) This package does not have downloadable releases.
[ERROR] (unite) This package does not have downloadable releases.
[INFO] (united-states-congress) This package is up to date.
[INFO] (unitedenergy-usage-data) Data has been updated for this package.
[INFO] (unitem) This package is up to date.
[INFO] (unitexlemmatizer) This package is up to date.
[INFO] (unithandler) Data has been updated for this package.
[INFO] (unithon) Data has been updated for this package.
[INFO] (unitify) This package is up to date.
[INFO] (unitig-caller) This package is up to date.
[INFO] (unitils) This package is up to date.
[INFO] (unitpay-python-sdk) This package is up to date.
[INFO] (unitprefix) This package is up to date.
[INFO] (unitrail) This package is up to date.
[INFO] (unitrans-evalir) This package is up to date.
[INFO] (units) This package is up to date.
[ERROR] (unitskumaster-pyforest) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (unitskumasterpyforest) Data has been updated for this package.
[INFO] (unitspec) This package is up to date.
[INFO] (unitstorm) This package is up to date.
[INFO] (unitstyle) This package is up to date.
[INFO] (unittest) This package is up to date.
[INFO] (unittest-additions) This package is up to date.
[INFO] (unittest-asserts) This package is up to date.
[INFO] (unittest-continuous) This package is up to date.
[INFO] (unittest-data-provider) This package is up to date.
[INFO] (unittest-dataprovider) This package is up to date.
[INFO] (unittest-expander) This package is up to date.
[INFO] (unittest-hooks) This package is up to date.
[INFO] (unittest-jasmine) This package is up to date.
[INFO] (unittest-jshint) This package is up to date.
[INFO] (unittest-mixins) This package is up to date.
[INFO] (unittest-onerror) This package is up to date.
[INFO] (unittest-parallel) This package is up to date.
[INFO] (unittest-prettify) This package is up to date.
[INFO] (unittest-pyspark) Data has been updated for this package.
[INFO] (unittest-resources) Data has been updated for this package.
[INFO] (unittest-sandbox) This package is up to date.
[INFO] (unittest-tap-reporting) This package is up to date.
[INFO] (unittest-utils) This package is up to date.
[INFO] (unittest-xml) This package is up to date.
[INFO] (unittest-xml-reporting) Data has been updated for this package.
[INFO] (unittest-xml-reporting-iron) This package is up to date.
[INFO] (unittest2) This package is up to date.
[INFO] (unittest2canopsis) This package is up to date.
[INFO] (unittest2py3k) This package is up to date.
[INFO] (unittest2pytest) This package is up to date.
[INFO] (unittest2six) This package is up to date.
[INFO] (unittester) This package is up to date.
[INFO] (unittestextras) This package is up to date.
[INFO] (unittestone) This package is up to date.
[INFO] (unittestrandgenstate) This package is up to date.
[INFO] (unittestxmlreporting) This package is up to date.
[INFO] (unittestzero) This package is up to date.
[INFO] (unitth) This package is up to date.
[ERROR] (unitvalue) This package does not have downloadable releases.
[INFO] (unity) This package is up to date.
[INFO] (unity-avindicator) This package is up to date.
[INFO] (unity-build-pipeline) This package is up to date.
[INFO] (unity-test-parser) Data has been updated for this package.
[INFO] (unityagents) This package is up to date.
[INFO] (unityapiclient) This package is up to date.
[INFO] (unitypack) This package is up to date.
[INFO] (unitypackage-extractor) Data has been updated for this package.
[INFO] (unityparser) Data has been updated for this package.
[INFO] (unitypy) Data has been updated for this package.
[INFO] (unityrde) Data has been updated for this package.
[INFO] (uniutils) This package is up to date.
[INFO] (univarfem) This package is up to date.
[INFO] (universa) Data has been updated for this package.
[INFO] (universal) This package is up to date.
[INFO] (universal-analytics-python) This package is up to date.
[INFO] (universal-analytics-python3) Data has been updated for this package.
[INFO] (universal-api-client) This package is up to date.
[INFO] (universal-divergence) This package is up to date.
[INFO] (universal-interferometer) This package is up to date.
[INFO] (universal-notifications) Data has been updated for this package.
[INFO] (universal-portfolios) This package is up to date.
[INFO] (universal-response-mobile-api) This package is up to date.
[INFO] (universal-rest-client) This package is up to date.
[INFO] (universal-usbtmc) This package is up to date.
[INFO] (universal-utils) This package is up to date.
[INFO] (universalbus) This package is up to date.
[INFO] (universalclient) This package is up to date.
[INFO] (universalid) This package is up to date.
[INFO] (universalmutator) Data has been updated for this package.
[INFO] (universalqueue) This package is up to date.
[INFO] (universaltranslator-evalir) This package is up to date.
[INFO] (universalwebscraping) This package is up to date.
[INFO] (universe) This package is up to date.
[INFO] (universion) This package is up to date.
[INFO] (universions) Data has been updated for this package.
[INFO] (universities) This package is up to date.
[INFO] (universityhack2018) This package is up to date.
[ERROR] (universvideo) Could not extract data from this package. See below for details.
"http://universvideo.org/UniversVideo-0.2.tar.gz" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/lib/python3.7/urllib/request.py", line 1319, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1347, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.7/urllib/request.py", line 1321, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

[INFO] (univider) Data has been updated for this package.
[INFO] (unix) This package is up to date.
[INFO] (unix-ar) This package is up to date.
[INFO] (unix-at) This package is up to date.
[INFO] (unix-daemon) This package is up to date.
[INFO] (unix-dates) This package is up to date.
[INFO] (unix-elf) This package is up to date.
[INFO] (unix-pyshell-pybc2) Data has been updated for this package.
[INFO] (unix-time) Data has been updated for this package.
[INFO] (unixaccount) This package is up to date.
[INFO] (unixdrive) Data has been updated for this package.
[INFO] (unixdump) This package is up to date.
[ERROR] (unixgram) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (unixpackage) This package is up to date.
[INFO] (unixpornposter) Data has been updated for this package.
[INFO] (unixsocketcs) This package is up to date.
[INFO] (unjsfuck) Data has been updated for this package.
[INFO] (unkchan) Data has been updated for this package.
[ERROR] (unknown) This package does not have downloadable releases.
[INFO] (unknownannei) Data has been updated for this package.
[INFO] (unknownhacker1125) This package is up to date.
[INFO] (unladenswallow) This package is up to date.
[INFO] (unleash) This package is up to date.
[INFO] (unleash-client) This package is up to date.
[INFO] (unleash-potential) This package is up to date.
[INFO] (unleashclient) Data has been updated for this package.
[INFO] (unleashed-py) Data has been updated for this package.
[INFO] (unlock) This package is up to date.
[INFO] (unlocker) This package is up to date.
[ERROR] (unlp) This package does not have downloadable releases.
[INFO] (unlzw) This package is up to date.
[INFO] (unmatcher) This package is up to date.
[INFO] (unmessage) This package is up to date.
[INFO] (unmock) This package is up to date.
[INFO] (unn) This package is up to date.
[INFO] (unnamed7389) This package is up to date.
[INFO] (unnamed998736) This package is up to date.
[INFO] (unnest-py) This package is up to date.
[INFO] (unnester) This package is up to date.
[INFO] (uno) This package is up to date.
[ERROR] (uno-deprecated) This package does not have downloadable releases.
[INFO] (unoccupied) This package is up to date.
[INFO] (unoconv) Data has been updated for this package.
[INFO] (unofficial-googleplay-api) This package is up to date.
[INFO] (unofficial-superset) Data has been updated for this package.
[INFO] (unophysics) Data has been updated for this package.
[INFO] (unormalize) This package is up to date.
[ERROR] (unos-allan) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (unotools) This package is up to date.
[INFO] (unounouno) This package is up to date.
[INFO] (unp) This package is up to date.
[INFO] (unpack) This package is up to date.
[INFO] (unpack200) This package is up to date.
[INFO] (unpacked) This package is up to date.
[INFO] (unpacklist) This package is up to date.
[INFO] (unpaddedbase32) Data has been updated for this package.
[INFO] (unpaddedbase64) This package is up to date.
[INFO] (unparse) This package is up to date.
[INFO] (unpdf) This package is up to date.
[INFO] (unpdfer) This package is up to date.
[INFO] (unplag) This package is up to date.
[INFO] (unplugged) Data has been updated for this package.
[INFO] (unpushed) This package is up to date.
[INFO] (unpy2exe) This package is up to date.
[INFO] (unpyclib) This package is up to date.
[INFO] (unpythonic) This package is up to date.
[INFO] (unqlite) This package is up to date.
[INFO] (unqlitepy) This package is up to date.
[INFO] (unrar) Data has been updated for this package.
[INFO] (unrar-cffi) Data has been updated for this package.
[INFO] (unrar-wrapper) This package is up to date.
[INFO] (unrardll) This package is up to date.
[INFO] (unrasterize) This package is up to date.
[INFO] (unread-decorator) This package is up to date.
[INFO] (unrealai) Data has been updated for this package.
[INFO] (unrealcv) This package is up to date.
[INFO] (unrealdb) Data has been updated for this package.
[INFO] (unrealistic) This package is up to date.
[INFO] (unred) This package is up to date.
[INFO] (unreferenced) This package is up to date.
[INFO] (unrest) This package is up to date.
[INFO] (unrestricted-advex) This package is up to date.
[INFO] (unroll) This package is up to date.
[INFO] (unrolr) Data has been updated for this package.
[INFO] (unrpa) Data has been updated for this package.
[INFO] (unrtf) This package is up to date.
[INFO] (unscii) Data has been updated for this package.
[INFO] (unscorer) This package is up to date.
[INFO] (unscramble) This package is up to date.
[INFO] (unscramble-me) This package is up to date.
[INFO] (unsee-dl) This package is up to date.
[INFO] (unseries) This package is up to date.
[INFO] (unsettings) This package is up to date.
[INFO] (unsh) This package is up to date.
[INFO] (unshare) Data has been updated for this package.
[INFO] (unshorten-ads) This package is up to date.
[ERROR] (unshortener) This package does not have downloadable releases.
[INFO] (unshortenit) This package is up to date.
[INFO] (unshred) This package is up to date.
[INFO] (unsonic) This package is up to date.
[INFO] (unsplash) This package is up to date.
[INFO] (unsplash-search) This package is up to date.
[INFO] (unsplashdownloader) This package is up to date.
[INFO] (unsplashpy) This package is up to date.
[INFO] (unsplashpython) Data has been updated for this package.
[INFO] (unspooler) This package is up to date.
[INFO] (unstable) This package is up to date.
[INFO] (unstats-rdf) This package is up to date.
[INFO] (unstdio) Data has been updated for this package.
[INFO] (unstdlib) Data has been updated for this package.
[INFO] (unsync) Data has been updated for this package.
[INFO] (untangle) This package is up to date.
[INFO] (untappd) This package is up to date.
[INFO] (untappd-crawler) This package is up to date.
[INFO] (untdl) This package is up to date.
[INFO] (untei) This package is up to date.
[INFO] (untestable) This package is up to date.
[INFO] (unties) This package is up to date.
[INFO] (until-nonidle) This package is up to date.
[INFO] (untiler) This package is up to date.
[INFO] (untilperfect) This package is up to date.
[INFO] (untimely) This package is up to date.
[INFO] (untinyurl) This package is up to date.
[INFO] (untitled) This package is up to date.
[INFO] (untitled-xj) This package is up to date.
[ERROR] (untitled1) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (untokenize) This package is up to date.
[INFO] (untp) This package is up to date.
[INFO] (untrack) This package is up to date.
[INFO] (untrendy) This package is up to date.
[INFO] (untroubled-spam-fetcher) This package is up to date.
[INFO] (untrusted) This package is up to date.
[INFO] (untt) This package is up to date.
[INFO] (untwisted) Data has been updated for this package.
[INFO] (unu) This package is up to date.
[INFO] (unum) This package is up to date.
[INFO] (unumpy) Data has been updated for this package.
[INFO] (unused-vue-components) This package is up to date.
[INFO] (unusefull) Data has been updated for this package.
[INFO] (unv-app) This package is up to date.
[INFO] (unv-deploy) Data has been updated for this package.
[INFO] (unv-utils) This package is up to date.
[INFO] (unv-web) Data has been updated for this package.
[INFO] (unvcf) This package is up to date.
[ERROR] (unveil) This package does not have downloadable releases.
[INFO] (unweb-iptc) This package is up to date.
[INFO] (unweb-recipe-ploneftp) This package is up to date.
[INFO] (unweb-recipe-uwsgi) This package is up to date.
[INFO] (unweb-shareit) This package is up to date.
[INFO] (unweb-watermark) This package is up to date.
[ERROR] (unwheel) This package does not have downloadable releases.
[INFO] (unwind) This package is up to date.
[INFO] (unwiredlabs) This package is up to date.
[INFO] (unwrap) This package is up to date.
[INFO] (unwrap-labels) Data has been updated for this package.
[INFO] (unwrapper) This package is up to date.
[INFO] (unxml) This package is up to date.
[INFO] (unyt) Data has been updated for this package.
[INFO] (unzipbomb) This package is up to date.
[ERROR] (unzipmbcs) This package does not have downloadable releases.
[INFO] (unzipper) This package is up to date.
[INFO] (uo-puddles) Data has been updated for this package.
[INFO] (uo-test-functions) This package is up to date.
[ERROR] (uofl-dztheme-simplesite) This package does not have downloadable releases.
[INFO] (uoftscrapers) This package is up to date.
[INFO] (uonet-request-signer) This package is up to date.
[INFO] (uorm) Data has been updated for this package.
[INFO] (uos-activpal) This package is up to date.
[INFO] (uos-cli) This package is up to date.
[INFO] (uotp) This package is up to date.
[INFO] (up) This package is up to date.
[INFO] (up-manager) This package is up to date.
[INFO] (up2cos) Data has been updated for this package.
[INFO] (up2oss) Data has been updated for this package.
[INFO] (up2qiniu) Data has been updated for this package.
[INFO] (up2smms) Data has been updated for this package.
[INFO] (up2upyun) Data has been updated for this package.
[INFO] (upaas-admin) This package is up to date.
[INFO] (upaas-client) This package is up to date.
[INFO] (upaas-common) This package is up to date.
[INFO] (upack) This package is up to date.
[INFO] (upackage) This package is up to date.
[INFO] (upandas) This package is up to date.
[INFO] (upapi) This package is up to date.
[INFO] (uparallel) This package is up to date.
[INFO] (uparse-python) This package is up to date.
[INFO] (upass) This package is up to date.
[INFO] (upath) This package is up to date.
[INFO] (upbeatlabs-mcp39f521) This package is up to date.
[INFO] (upbit) This package is up to date.
[INFO] (upbitpy) This package is up to date.
[INFO] (upc) This package is up to date.
[INFO] (upc-checker-pyo3) Data has been updated for this package.
[INFO] (upc-item-db-api) This package is up to date.
[INFO] (upc-remotecontrol) This package is up to date.
[INFO] (upcdb) This package is up to date.
[INFO] (upckonxtest) Data has been updated for this package.
[INFO] (upcloud) This package is up to date.
[INFO] (upcloud-api) Data has been updated for this package.
[INFO] (upcloud-api-python) This package is up to date.
[INFO] (upctools) This package is up to date.
[INFO] (upd89) This package is up to date.
[INFO] (updatable) Data has been updated for this package.
[INFO] (updatable-zipfile) This package is up to date.
[INFO] (update) This package is up to date.
[INFO] (update-checker) This package is up to date.
[INFO] (update-checker-app) This package is up to date.
[INFO] (update-conf-py) This package is up to date.
[INFO] (update-copyright) This package is up to date.
[INFO] (update-dotdee) This package is up to date.
[INFO] (update-he-dns) This package is up to date.
[INFO] (update-ip) This package is up to date.
[INFO] (update-notipy) This package is up to date.
[INFO] (update-package-version) This package is up to date.
[INFO] (update-plex) This package is up to date.
[INFO] (update-plex-music-album-covers) Data has been updated for this package.
[INFO] (update-repo) Data has been updated for this package.
[INFO] (update-req-spec) This package is up to date.
[INFO] (update-route53) This package is up to date.
[INFO] (update-tool) This package is up to date.
[INFO] (update-wrapper) This package is up to date.
[INFO] (updatechecker) This package is up to date.
[INFO] (updatedir) This package is up to date.
[INFO] (updatedpip) This package is up to date.
[INFO] (updatehdr) This package is up to date.
[INFO] (updatehub-agent-sdk) This package is up to date.
[INFO] (updatehub-package-schema) This package is up to date.
[INFO] (updater) Data has been updated for this package.
[INFO] (updater4pyi) This package is up to date.
[INFO] (updaterforexe) Data has been updated for this package.
[INFO] (updates) This package is up to date.
[INFO] (updatesystem) This package is up to date.
[INFO] (updatetable) This package is up to date.
[INFO] (updatorr) This package is up to date.
[INFO] (updelipack) Data has been updated for this package.
[INFO] (updian) This package is up to date.
[INFO] (updistributions) Data has been updated for this package.
[INFO] (updoc) This package is up to date.
[INFO] (updog) Data has been updated for this package.
[INFO] (updoon) This package is up to date.
[INFO] (updown) This package is up to date.
[INFO] (upenwrt) Data has been updated for this package.
[INFO] (uperations-base) This package is up to date.
[INFO] (uperations-kernel) This package is up to date.
[INFO] (upersetter) This package is up to date.
[INFO] (upf-to-json) Data has been updated for this package.
[INFO] (upfluence-thrift) This package is up to date.
[INFO] (upfluence-utils) This package is up to date.
[INFO] (upfp) This package is up to date.
[ERROR] (upfront-cognitivelevelpredictor) This package does not have downloadable releases.
[INFO] (upfront-foldercontents) This package is up to date.
[INFO] (upfront-navportlet) This package is up to date.
[INFO] (upfront-simplereferencefield) This package is up to date.
[ERROR] (upgrade) This package does not have downloadable releases.
[INFO] (upgrade-ensurepip) This package is up to date.
[INFO] (upgrade-requirements) This package is up to date.
[INFO] (upgraded-engineer) Data has been updated for this package.
[INFO] (upgradegit) This package is up to date.
[INFO] (upguard) Data has been updated for this package.
[INFO] (uphold-python3) This package is up to date.
[INFO] (upicasa) This package is up to date.
[ERROR] (upip) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (upipe) This package does not have downloadable releases.
[INFO] (upkeep) Data has been updated for this package.
[INFO] (upkg) This package is up to date.
[INFO] (upkit) This package is up to date.
[INFO] (uplay) Data has been updated for this package.
[INFO] (upld-tester-1) This package is up to date.
[INFO] (uplift) This package is up to date.
[INFO] (uplink) This package is up to date.
[INFO] (uplink-httpx) Data has been updated for this package.
[INFO] (uplink-protobuf) This package is up to date.
[INFO] (upload) This package is up to date.
[INFO] (upload-chain-eth) This package is up to date.
[INFO] (upload-dnatools) This package is up to date.
[INFO] (upload-dnatools-2) This package is up to date.
[INFO] (upload-dnatools-3) This package is up to date.
[INFO] (upload-dnatools-35) This package is up to date.
[INFO] (upload-dnatools-36) This package is up to date.
[INFO] (upload-dnatools1) This package is up to date.
[INFO] (upload-file-s3) This package is up to date.
[INFO] (upload-haddocks) This package is up to date.
[INFO] (upload-insert-tools) This package is up to date.
[INFO] (uploada) Data has been updated for this package.
[INFO] (uploadcare-migro) This package is up to date.
[INFO] (uploaddownloadfilescsc440) This package is up to date.
[INFO] (uploader) This package is up to date.
[INFO] (uploaderjs) This package is up to date.
[INFO] (uploadfu) This package is up to date.
[INFO] (uploadossfile) This package is up to date.
[INFO] (uploadserver) This package is up to date.
[INFO] (uploadtest) This package is up to date.
[INFO] (uploadtesting-y) This package is up to date.
[INFO] (uploadtestingy) This package is up to date.
[INFO] (uploadview) This package is up to date.
[INFO] (uploadwithus) This package is up to date.
[INFO] (uplook) This package is up to date.
[INFO] (uplooking) This package is up to date.
[ERROR] (upm) This package does not have downloadable releases.
[INFO] (upmcli) This package is up to date.
[INFO] (upme) This package is up to date.
[INFO] (upmost-beta) This package is up to date.
[INFO] (upnp) This package is up to date.
[INFO] (upnp-inspector) This package is up to date.
[INFO] (upnp-map) This package is up to date.
[INFO] (upnpclient) This package is up to date.
[INFO] (upnpport) This package is up to date.
[INFO] (upnpy) Data has been updated for this package.
[INFO] (upodder) This package is up to date.
[INFO] (upoints) This package is up to date.
[INFO] (upper-50) This package is up to date.
[INFO] (uppercut) Data has been updated for this package.
[INFO] (uppsell) This package is up to date.
[INFO] (upr) This package is up to date.
[ERROR] (upraise) This package does not have downloadable releases.
[INFO] (upref) Data has been updated for this package.
[INFO] (uprefix) This package is up to date.
[INFO] (uprime) This package is up to date.
[INFO] (uproot) Data has been updated for this package.
[INFO] (uproot-methods) Data has been updated for this package.
[INFO] (uproxy) This package is up to date.
[INFO] (ups) This package is up to date.
[INFO] (ups-api) Data has been updated for this package.
[INFO] (ups-utils) This package is up to date.
[INFO] (upscrot) Data has been updated for this package.
[INFO] (upsearch) This package is up to date.
[INFO] (upsert) This package is up to date.
[INFO] (upsetplot) This package is up to date.
[INFO] (upside-down-rl) Data has been updated for this package.
[INFO] (upsidedown) This package is up to date.
[INFO] (upsilon) Data has been updated for this package.
[INFO] (upsilont) This package is up to date.
[INFO] (upsmychoice) This package is up to date.
[INFO] (upsourceapi) This package is up to date.
[INFO] (upstart) This package is up to date.
[INFO] (upstart-dev) This package is up to date.
[INFO] (upstart-new) This package is up to date.
[INFO] (upstox) This package is up to date.
[INFO] (upsty) Data has been updated for this package.
[INFO] (upt) Data has been updated for this package.
[INFO] (upt-cpan) Data has been updated for this package.
[INFO] (upt-cran) Data has been updated for this package.
[INFO] (upt-debian) This package is up to date.
[INFO] (upt-fedora) Data has been updated for this package.
[INFO] (upt-freebsd) Data has been updated for this package.
[INFO] (upt-guix) This package is up to date.
[INFO] (upt-nix) This package is up to date.
[INFO] (upt-openbsd) This package is up to date.
[INFO] (upt-pypi) Data has been updated for this package.
[INFO] (upt-rubygems) Data has been updated for this package.
[INFO] (uptask) This package is up to date.
[INFO] (uptick) Data has been updated for this package.
[INFO] (uptide) Data has been updated for this package.
[INFO] (uptime) This package is up to date.
[INFO] (uptimerobotpy) This package is up to date.
[INFO] (uptodate) This package is up to date.
[INFO] (uptool) This package is up to date.
[INFO] (uptr) This package is up to date.
[INFO] (uptrack) This package is up to date.
[INFO] (uptt) Data has been updated for this package.
[ERROR] (upup-essays) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (upversion) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (upvest) Data has been updated for this package.
[INFO] (upvest-cli) Data has been updated for this package.
[INFO] (upy) This package is up to date.
[INFO] (upydev) Data has been updated for this package.
[INFO] (upydevice) Data has been updated for this package.
[ERROR] (upyflashed) This package does not have downloadable releases.
[INFO] (upylib) This package is up to date.
[INFO] (upyls) This package is up to date.
[INFO] (upysm) This package is up to date.
[INFO] (upython) Data has been updated for this package.
[INFO] (upytimerobot) This package is up to date.
[INFO] (upyun) Data has been updated for this package.
[INFO] (upyun-cli) This package is up to date.
[INFO] (upyun-django) This package is up to date.
[INFO] (uq) This package is up to date.
[INFO] (uqbar) Data has been updated for this package.
[INFO] (uqer) Data has been updated for this package.
[INFO] (uqid) This package is up to date.
[INFO] (uqpy) Data has been updated for this package.
[INFO] (uqtie) Data has been updated for this package.
[INFO] (uqtoolbox) This package is up to date.
[INFO] (ur-cb2) This package is up to date.
[INFO] (ur-rtde) Data has been updated for this package.
[INFO] (ur1) This package is up to date.
[INFO] (uraeus) Data has been updated for this package.
[INFO] (uraeus-nmbd-python) Data has been updated for this package.
[INFO] (uraeus-smbd) Data has been updated for this package.
[INFO] (ural) Data has been updated for this package.
[INFO] (uralicnlp) This package is up to date.
[INFO] (uranium) Data has been updated for this package.
[INFO] (uranium-plus) This package is up to date.
[INFO] (uranus) This package is up to date.
[INFO] (uranuspy) This package is up to date.
[INFO] (urbackup-server-web-api-wrapper) This package is up to date.
[ERROR] (urban) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (urban-async) This package is up to date.
[INFO] (urban-dictionary-parser-py) Data has been updated for this package.
[INFO] (urban-env) This package is up to date.
[INFO] (urban-footprinter) Data has been updated for this package.
[INFO] (urban-metagenomics-tutorial) Data has been updated for this package.
[INFO] (urban-physiology-toolkit) This package is up to date.
[INFO] (urban-py) This package is up to date.
[INFO] (urbanaccess) This package is up to date.
[INFO] (urbanairship) This package is up to date.
[INFO] (urbanairship3) This package is up to date.
[INFO] (urbandefinition) This package is up to date.
[INFO] (urbandict) Data has been updated for this package.
[INFO] (urbandictionary) This package is up to date.
[INFO] (urbandictionary-top) This package is up to date.
[INFO] (urbanmediator) This package is up to date.
[INFO] (urbanpyctionary) This package is up to date.
[INFO] (urbansim) This package is up to date.
[INFO] (urbansim-defaults) Data has been updated for this package.
[INFO] (urbansim-templates) Data has been updated for this package.
[INFO] (urbansmartflood) This package is up to date.
[INFO] (urcalc) This package is up to date.
[INFO] (urconf) This package is up to date.
[INFO] (urdf-parser-py) This package is up to date.
[INFO] (urdf2webots) Data has been updated for this package.
[INFO] (urdfpy) Data has been updated for this package.
[INFO] (urdubiometer) Data has been updated for this package.
[INFO] (urduhack) Data has been updated for this package.
[INFO] (ureactme) This package is up to date.
[INFO] (urecon) This package is up to date.
[INFO] (urecord) This package is up to date.
[INFO] (urequests) This package is up to date.
[INFO] (urest) This package is up to date.
[INFO] (urestapi) Data has been updated for this package.
[INFO] (urf) This package is up to date.
[INFO] (urgent11-detector) Data has been updated for this package.
[INFO] (urh) Data has been updated for this package.
[INFO] (uri) This package is up to date.
[INFO] (uri-handler) Data has been updated for this package.
[INFO] (uriah-nester) This package is up to date.
[INFO] (uriah-print) This package is up to date.
[INFO] (uribuilder) This package is up to date.
[INFO] (uric) This package is up to date.
[INFO] (uricache) This package is up to date.
[INFO] (uricli) This package is up to date.
[INFO] (uricore) This package is up to date.
[INFO] (urihandler) This package is up to date.
[INFO] (urilib) This package is up to date.
[INFO] (uriref) This package is up to date.
[INFO] (uriregistry) This package is up to date.
[INFO] (uritemplate) Data has been updated for this package.
[INFO] (uritemplate-py) This package is up to date.
[INFO] (uritemplatepy) This package is up to date.
[INFO] (uritool) This package is up to date.
[INFO] (uritools) Data has been updated for this package.
[INFO] (uriutil) This package is up to date.
[INFO] (uriutils) This package is up to date.
[INFO] (url) This package is up to date.
[INFO] (url-checker) This package is up to date.
[INFO] (url-clustering) Data has been updated for this package.
[INFO] (url-downloader) Data has been updated for this package.
[INFO] (url-extract) This package is up to date.
[INFO] (url-extractor) This package is up to date.
[INFO] (url-for-s3) This package is up to date.
[INFO] (url-generator) This package is up to date.
[INFO] (url-matchers) This package is up to date.
[INFO] (url-mon) This package is up to date.
[INFO] (url-normalize) This package is up to date.
[INFO] (url-obfuscate) This package is up to date.
[INFO] (url-package) This package is up to date.
[INFO] (url-regex) Data has been updated for this package.
[INFO] (url-request-scheduler) Data has been updated for this package.
[INFO] (url-shortener) This package is up to date.
[INFO] (url-summary) This package is up to date.
[INFO] (url2env) This package is up to date.
[INFO] (url2feed) This package is up to date.
[INFO] (url2kindle) Data has been updated for this package.
[INFO] (url2markdown-cli) This package is up to date.
[INFO] (url2tree) Data has been updated for this package.
[INFO] (url2vapi) This package is up to date.
[INFO] (url2word) This package is up to date.
[INFO] (url64) Data has been updated for this package.
[INFO] (urlarchiver) This package is up to date.
[INFO] (urlauth) This package is up to date.
[INFO] (urlblocks) This package is up to date.
[INFO] (urlbuilder) This package is up to date.
[INFO] (urlcan) This package is up to date.
[INFO] (urlcanon) This package is up to date.
[INFO] (urlclean) This package is up to date.
[INFO] (urlclustering) This package is up to date.
[INFO] (urlconvert) This package is up to date.
[INFO] (urldecode) This package is up to date.
[ERROR] (urldetect) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (urledit) This package is up to date.
[INFO] (urlencoder) This package is up to date.
[INFO] (urler) This package is up to date.
[INFO] (urlexpander) This package is up to date.
[INFO] (urlextract) Data has been updated for this package.
[INFO] (urlextract-py2-7) This package is up to date.
[INFO] (urlfetch) Data has been updated for this package.
[INFO] (urlfiddler) Data has been updated for this package.
[INFO] (urlfinder) This package is up to date.
[INFO] (urlfinderlib) Data has been updated for this package.
[INFO] (urlfit) This package is up to date.
[INFO] (urlformat) This package is up to date.
[INFO] (urlget) This package is up to date.
[INFO] (urlgrabber) Data has been updated for this package.
[INFO] (urlhelp) This package is up to date.
[INFO] (urlhmac) This package is up to date.
[INFO] (urlifyhelper) This package is up to date.
[INFO] (urlimage) Data has been updated for this package.
[INFO] (urlimage-dcollien) Data has been updated for this package.
[INFO] (urlimport) This package is up to date.
[INFO] (urljects) This package is up to date.
[INFO] (urljoin) This package is up to date.
[INFO] (urllib-gssapi) This package is up to date.
[INFO] (urllib-kerberos) This package is up to date.
[INFO] (urllib-s3) This package is up to date.
[INFO] (urllib2-file) This package is up to date.
[INFO] (urllib2-kerberos) This package is up to date.
[INFO] (urllib2-prior-auth) This package is up to date.
[INFO] (urllib3) Data has been updated for this package.
[INFO] (urllib3-fixed) Data has been updated for this package.
[INFO] (urllib3-mock) This package is up to date.
[ERROR] (urllib4) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "http://code.google.com/p/urllib4/downloads/list"
[INFO] (urllib5) This package is up to date.
[INFO] (urllibcache) This package is up to date.
[INFO] (urlman) Data has been updated for this package.
[ERROR] (urlmap) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "https://nodeload.github.com/0wls/urlmap/zipball/master"
[INFO] (urlmark) This package is up to date.
[INFO] (urlmatch) This package is up to date.
[INFO] (urlminer) This package is up to date.
[INFO] (urlmon) This package is up to date.
[INFO] (urlmonitor) Data has been updated for this package.
[INFO] (urlnorm) This package is up to date.
[INFO] (urlnormalizer) Data has been updated for this package.
[INFO] (urlobject) This package is up to date.
[INFO] (urlopen) This package is up to date.
[INFO] (urlp) Data has been updated for this package.
[INFO] (urlparse2) This package is up to date.
[INFO] (urlparse3) This package is up to date.
[INFO] (urlparse4) This package is up to date.
[INFO] (urlparser) This package is up to date.
[INFO] (urlpath) This package is up to date.
[INFO] (urlpathlib) This package is up to date.
[INFO] (urlprase) This package is up to date.
[INFO] (urlquery) This package is up to date.
[INFO] (urlquick) This package is up to date.
[INFO] (urlquote) Data has been updated for this package.
[INFO] (urlrap) This package is up to date.
[INFO] (urlreader) Data has been updated for this package.
[INFO] (urlrelay) This package is up to date.
[INFO] (urlreplacer) This package is up to date.
[ERROR] (urls) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (urlsafecrypt) This package is up to date.
[INFO] (urlscan) Data has been updated for this package.
[INFO] (urlscan-py) Data has been updated for this package.
[INFO] (urlscanio) Data has been updated for this package.
[INFO] (urlsearch) This package is up to date.
[INFO] (urlshortener) Data has been updated for this package.
[INFO] (urlshortener-cli) This package is up to date.
[INFO] (urlshortner) This package is up to date.
[INFO] (urlshots-api) This package is up to date.
[INFO] (urlsigner) This package is up to date.
[INFO] (urlspy) Data has been updated for this package.
[INFO] (urlsresolver) This package is up to date.
[INFO] (urlstore) This package is up to date.
[INFO] (urlstring) This package is up to date.
[INFO] (urltest) This package is up to date.
[INFO] (urltitle) Data has been updated for this package.
[INFO] (urltojson) This package is up to date.
[INFO] (urltomd) This package is up to date.
[INFO] (urltools) This package is up to date.
[INFO] (urltree) This package is up to date.
[INFO] (urlunshort) This package is up to date.
[INFO] (urlunshort3) Data has been updated for this package.
[INFO] (urlup) This package is up to date.
[INFO] (urlvalidator) This package is up to date.
[INFO] (urlwait) This package is up to date.
[INFO] (urlwait2) This package is up to date.
[INFO] (urlwatch) This package is up to date.
[INFO] (urly) This package is up to date.
[INFO] (urlymath) This package is up to date.
[INFO] (urmem) This package is up to date.
[INFO] (urnai) Data has been updated for this package.
[INFO] (uroboros) Data has been updated for this package.
[INFO] (uropa) Data has been updated for this package.
[INFO] (urouter) Data has been updated for this package.
[INFO] (urp) This package is up to date.
[INFO] (urpc) This package is up to date.
[ERROR] (ursa) This package does not have downloadable releases.
[INFO] (ursa-major) Data has been updated for this package.
[INFO] (ursa2) This package is up to date.
[INFO] (ursabot) Data has been updated for this package.
[INFO] (ursacl) Data has been updated for this package.
[INFO] (ursadb) This package is up to date.
[INFO] (ursctl) Data has been updated for this package.
[INFO] (ursekar-distributions) Data has been updated for this package.
[INFO] (ursgal) Data has been updated for this package.
[INFO] (ursine) This package is up to date.
[INFO] (urssus) This package is up to date.
[INFO] (urt) This package is up to date.
[INFO] (urtc) This package is up to date.
[INFO] (urtimer) This package is up to date.
[INFO] (urtoday) This package is up to date.
[INFO] (urubu) This package is up to date.
[ERROR] (urutu) This package does not have downloadable releases.
[INFO] (urwid) Data has been updated for this package.
[INFO] (urwid-geventloop) This package is up to date.
[INFO] (urwid-pydux) This package is up to date.
[INFO] (urwid-readline) Data has been updated for this package.
[INFO] (urwid-satext) Data has been updated for this package.
[INFO] (urwid-stackedwidget) This package is up to date.
[INFO] (urwid-timed-progress) This package is up to date.
[INFO] (urwid-todos) This package is up to date.
[INFO] (urwid-ueberzogen) Data has been updated for this package.
[INFO] (urwid-utils) This package is up to date.
[INFO] (urwid-viedit) This package is up to date.
[INFO] (urwide) This package is up to date.
[INFO] (urwidtrees) This package is up to date.
[INFO] (urx) This package is up to date.
[INFO] (urxui) This package is up to date.
[INFO] (urxvt-tabbed) This package is up to date.
[INFO] (us) This package is up to date.
[INFO] (us-census) This package is up to date.
[INFO] (us-elections) Data has been updated for this package.
[INFO] (us-geo-helper) This package is up to date.
[INFO] (us-netview-non-major) Data has been updated for this package.
[INFO] (us-polygon-mapper) This package is up to date.
[ERROR] (us-pyton-utils) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (us3) This package is up to date.
[ERROR] (usa) This package does not have downloadable releases.
[INFO] (usa-spending) This package is up to date.
[INFO] (usa-today) This package is up to date.
[INFO] (usabilla-api) This package is up to date.
[INFO] (usace-public-notices) This package is up to date.
[INFO] (usaddress) This package is up to date.
[INFO] (usaddress-scourgify) Data has been updated for this package.
[INFO] (usafe) This package is up to date.
[INFO] (usage) This package is up to date.
[INFO] (usageapi) This package is up to date.
[INFO] (usagelogger) Data has been updated for this package.
[INFO] (usagestats) Data has been updated for this package.
[INFO] (usagi) This package is up to date.
[INFO] (usain) This package is up to date.
[INFO] (usajobs) This package is up to date.
[ERROR] (usb-barcode-scanner) Could not extract data from this package. See below for details.
"https://files.pythonhosted.org/packages/76/6a/de8a49caa41afcc613dcb986c048ab433ef51c2321b381032f3100374617/usb%20barcode%20scanner-0.3.tar.gz" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (usb-can-analyzer) Data has been updated for this package.
[INFO] (usb-iss) Data has been updated for this package.
[INFO] (usb-manager) This package is up to date.
[INFO] (usb-ser-mon) This package is up to date.
[INFO] (usb1208fs) This package is up to date.
[INFO] (usb2container) Data has been updated for this package.
[INFO] (usb4a) This package is up to date.
[INFO] (usbarm) This package is up to date.
[INFO] (usbclassifier) This package is up to date.
[INFO] (usbdev) Data has been updated for this package.
[INFO] (usbgen) This package is up to date.
[INFO] (usbguard-simple-gui-py-qt) Data has been updated for this package.
[INFO] (usbid) This package is up to date.
[INFO] (usbinfo) This package is up to date.
[INFO] (usblamp) This package is up to date.
[INFO] (usblock) This package is up to date.
[INFO] (usbrip) Data has been updated for this package.
[INFO] (usbrply) This package is up to date.
[INFO] (usbsdmux) Data has been updated for this package.
[INFO] (usbserial4a) This package is up to date.
[INFO] (usbusiness) This package is up to date.
[INFO] (usc-schedule) Data has been updated for this package.
[INFO] (uscensus) This package is up to date.
[INFO] (uscisstatus) This package is up to date.
[INFO] (uscrape) This package is up to date.
[INFO] (usdt) This package is up to date.
[INFO] (use) This package is up to date.
[INFO] (use-context) This package is up to date.
[INFO] (use-dir) Data has been updated for this package.
[INFO] (use-logging) This package is up to date.
[INFO] (use0mk) This package is up to date.
[INFO] (usedave) Data has been updated for this package.
[INFO] (usedef) This package is up to date.
[INFO] (useful) Data has been updated for this package.
[INFO] (useful-collections) This package is up to date.
[INFO] (useful-decoration) Data has been updated for this package.
[INFO] (useful-graphs) This package is up to date.
[INFO] (useful-inkleby) This package is up to date.
[INFO] (useful-tools) Data has been updated for this package.
[INFO] (useful-wsi) Data has been updated for this package.
[INFO] (usefuldb) This package is up to date.
[INFO] (usefulpy) Data has been updated for this package.
[ERROR] (usefulutil) This package does not have downloadable releases.
[INFO] (usefulutils) This package is up to date.
[INFO] (useintest) This package is up to date.
[INFO] (usejenkins) This package is up to date.
[INFO] (useless) This package is up to date.
[INFO] (useless-pipes) This package is up to date.
[INFO] (useless-py) This package is up to date.
[INFO] (useless-utils) This package is up to date.
[INFO] (usementionerror) This package is up to date.
[INFO] (usemoduleprint) This package is up to date.
[INFO] (usephysics) Data has been updated for this package.
[ERROR] (useppm) This package does not have downloadable releases.
[INFO] (useppy) This package is up to date.
[INFO] (user-agent) This package is up to date.
[INFO] (user-agent-middleware) This package is up to date.
[INFO] (user-agents) This package is up to date.
[INFO] (user-agents-next) This package is up to date.
[INFO] (user-api) This package is up to date.
[INFO] (user-auth) Data has been updated for this package.
[INFO] (user-behavior) This package is up to date.
[INFO] (user-blueprint) This package is up to date.
[INFO] (user-config) This package is up to date.
[INFO] (user-manager) Data has been updated for this package.
[INFO] (user-manager-pkg) Data has been updated for this package.
[INFO] (user-messages) This package is up to date.
[INFO] (user-profile) This package is up to date.
[INFO] (user-provision-tool) This package is up to date.
[INFO] (user-query-optimizer) This package is up to date.
[INFO] (user-sdk) Data has been updated for this package.
[INFO] (user-util) This package is up to date.
[INFO] (user-voting-rocks) This package is up to date.
[INFO] (user12345678) This package is up to date.
[INFO] (useragent) This package is up to date.
[INFO] (useragent-pool) This package is up to date.
[INFO] (useragent-xxc) Data has been updated for this package.
[INFO] (useragents) This package is up to date.
[INFO] (useragentutils) This package is up to date.
[INFO] (useragentxxc) Data has been updated for this package.
[INFO] (userapp) This package is up to date.
[INFO] (userapp-cli) This package is up to date.
[INFO] (userapp-tornado) This package is up to date.
[ERROR] (userbackup) Could not extract data from this package. See below for details.
"http://perso.wanadoo.fr/astra/userbackup/userbackup-0.1.tar.gz" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (userbase) This package is up to date.
[INFO] (userbased-nc-bench) This package is up to date.
[INFO] (usercheck) This package is up to date.
[INFO] (userconf) Data has been updated for this package.
[ERROR] (userconfig) Could not extract data from this package. See below for details.
"http://userconfig.googlecode.com/files/userconfig-1.0.9-py2.5.egg" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (usercustomize) This package is up to date.
[INFO] (usercustomize3264) This package is up to date.
[INFO] (userdata-cool) This package is up to date.
[INFO] (userdatamodel) Data has been updated for this package.
[ERROR] (userdefaults) This package does not have downloadable releases.
[ERROR] (userdock) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (userdocker) This package is up to date.
[INFO] (useresponse) This package is up to date.
[INFO] (userexit) This package is up to date.
[INFO] (userful) This package is up to date.
[INFO] (usergrid) This package is up to date.
[INFO] (usergrid-tools) This package is up to date.
[ERROR] (usergrid-util) Could not extract data from this package. See below for details.
".0.2" extension not supported.
[INFO] (usergrid-utils) This package is up to date.
[INFO] (userhawk) Data has been updated for this package.
[INFO] (userimageprocessing) This package is up to date.
[INFO] (userinput) Data has been updated for this package.
[INFO] (userkit) Data has been updated for this package.
[INFO] (usermanager) This package is up to date.
[INFO] (usermanager-guzman) This package is up to date.
[INFO] (username) This package is up to date.
[INFO] (username-cli) This package is up to date.
[INFO] (username-generator) This package is up to date.
[INFO] (username-validator) This package is up to date.
[INFO] (usernameccplugin) This package is up to date.
[INFO] (usernamegen) This package is up to date.
[INFO] (userpass) This package is up to date.
[INFO] (userpath) Data has been updated for this package.
[INFO] (userpaths) Data has been updated for this package.
[INFO] (userprediction) This package is up to date.
[INFO] (userprofile) This package is up to date.
[INFO] (users) This package is up to date.
[INFO] (userschema) This package is up to date.
[INFO] (usersettings) This package is up to date.
[INFO] (usersgithub) This package is up to date.
[INFO] (userspacefs) This package is up to date.
[INFO] (userspy) This package is up to date.
[INFO] (userstorage) Data has been updated for this package.
[INFO] (usertrue) This package is up to date.
[INFO] (userutils) This package is up to date.
[INFO] (userv) Data has been updated for this package.
[INFO] (userv-async-server) This package is up to date.
[INFO] (userv-socket-server) This package is up to date.
[INFO] (uservice-logging) This package is up to date.
[INFO] (uservice-utils) This package is up to date.
[INFO] (uservoice) Data has been updated for this package.
[INFO] (usethis-django-bootstrap) This package is up to date.
[INFO] (useurmind-mkdocs-macros-plugin) This package is up to date.
[INFO] (usexif) This package is up to date.
[INFO] (usfm) This package is up to date.
[INFO] (usfm-references) Data has been updated for this package.
[INFO] (usfm-tools) Data has been updated for this package.
[INFO] (usfm-tools-py3) Data has been updated for this package.
[INFO] (usfm-utils) This package is up to date.
[INFO] (usfm2osis) This package is up to date.
[INFO] (usginmodels) This package is up to date.
[INFO] (usgota) Data has been updated for this package.
[INFO] (usgs) This package is up to date.
[INFO] (usgs-api) This package is up to date.
[INFO] (usgs-shakecast) Data has been updated for this package.
[ERROR] (usgsdata-citiesx020) This package does not have downloadable releases.
[INFO] (usgsdownload) This package is up to date.
[INFO] (ush) Data has been updated for this package.
[INFO] (ushahidi-sphinx-rtd-theme) This package is up to date.
[INFO] (ushapy) This package is up to date.
[INFO] (usher) This package is up to date.
[INFO] (ushlex) This package is up to date.
[INFO] (ushuffle) This package is up to date.
[INFO] (usienarl) Data has been updated for this package.
[INFO] (usig-normalizador-amba) This package is up to date.
[INFO] (usig-normalizador-amba-p32) This package is up to date.
[INFO] (usigtreatment) This package is up to date.
[INFO] (usim) Data has been updated for this package.
[INFO] (usim800) This package is up to date.
[INFO] (usine) Data has been updated for this package.
[ERROR] (usingnamespace) This package does not have downloadable releases.
[INFO] (usiq) This package is up to date.
[INFO] (usit) Data has been updated for this package.
[INFO] (usmart-sdk) This package is up to date.
[INFO] (usncarve) This package is up to date.
[INFO] (usnews-scrapper) This package is up to date.
[INFO] (usnparser) This package is up to date.
[INFO] (usolitaire) This package is up to date.
[INFO] (usonic) This package is up to date.
[INFO] (uspech) This package is up to date.
[ERROR] (usphinx) This package does not have downloadable releases.
[INFO] (uspp-universal-serial-port-python-library) This package is up to date.
[INFO] (usps-api) This package is up to date.
[INFO] (usps-client) This package is up to date.
[INFO] (uspto-opendata-python) This package is up to date.
[INFO] (usql) Data has been updated for this package.
[INFO] (usr) This package is up to date.
[INFO] (usr-r16) Data has been updated for this package.
[INFO] (usresmonitor) This package is up to date.
[INFO] (usrsvc) This package is up to date.
[INFO] (ussclicore) This package is up to date.
[INFO] (ussd-airflow) Data has been updated for this package.
[INFO] (ussd-airflow-engine) Data has been updated for this package.
[INFO] (ussd-elastic-apm) Data has been updated for this package.
[INFO] (ussd-session) This package is up to date.
[INFO] (usshapes) This package is up to date.
[INFO] (ustack-etl) This package is up to date.
[INFO] (ustack-logging) This package is up to date.
[INFO] (ustack-tornado-shutdown) This package is up to date.
[INFO] (ustackdocstheme) Data has been updated for this package.
[INFO] (ustccomplex) Data has been updated for this package.
[INFO] (ustciscr) Data has been updated for this package.
[INFO] (ustciscrqin) Data has been updated for this package.
[INFO] (ustcjiaqi) Data has been updated for this package.
[INFO] (ustclnk) This package is up to date.
[INFO] (ustcnlp) This package is up to date.
[INFO] (ustorage) Data has been updated for this package.
[INFO] (ustubby) Data has been updated for this package.
[INFO] (ustudio-hmac-tornado) This package is up to date.
[INFO] (usuarioapppackagegeo) This package is up to date.
[INFO] (usuarios-cpf-django) Data has been updated for this package.
[ERROR] (usufy) This package does not have downloadable releases.
[ERROR] (usurp) This package does not have downloadable releases.
[INFO] (usurper) This package is up to date.
[INFO] (usury) This package is up to date.
[INFO] (uswoodnester) This package is up to date.
[INFO] (usyslog) This package is up to date.
[INFO] (uszipcode) Data has been updated for this package.
[INFO] (ut) This package is up to date.
[INFO] (ut-nester) This package is up to date.
[INFO] (ut2chartrender) Data has been updated for this package.
[INFO] (ut2d) This package is up to date.
[INFO] (ut61e) This package is up to date.
[INFO] (uta) This package is up to date.
[INFO] (uta-align) This package is up to date.
[INFO] (utagent) This package is up to date.
[INFO] (utah) This package is up to date.
[INFO] (utailbase) Data has been updated for this package.
[INFO] (utailfilehash) This package is up to date.
[INFO] (utalm) Data has been updated for this package.
[INFO] (utalm-bash) Data has been updated for this package.
[INFO] (utalm-c) Data has been updated for this package.
[INFO] (utalm-cpp) Data has been updated for this package.
[INFO] (utalm-java) Data has been updated for this package.
[INFO] (utalm-javascript) Data has been updated for this package.
[INFO] (utalm-python) Data has been updated for this package.
[INFO] (utaskweb) This package is up to date.
[INFO] (utaw) This package is up to date.
[INFO] (utbone) This package is up to date.
[INFO] (utc) This package is up to date.
[INFO] (utcdatetime) This package is up to date.
[INFO] (utcdtw-cffi) This package is up to date.
[INFO] (utcformatter) This package is up to date.
[INFO] (utcondor) This package is up to date.
[INFO] (utempid) Data has been updated for this package.
[INFO] (utemplate) Data has been updated for this package.
[INFO] (utensils) This package is up to date.
[INFO] (utensor-cgen) Data has been updated for this package.
[INFO] (uterm) This package is up to date.
[INFO] (utest) This package is up to date.
[INFO] (utf-remote) This package is up to date.
[INFO] (utf7) This package is up to date.
[ERROR] (utf8) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (utf8-codepoint) This package is up to date.
[INFO] (utf8-escape) This package is up to date.
[INFO] (utf8cleaner) Data has been updated for this package.
[INFO] (utf8config) This package is up to date.
[INFO] (utf8forgood) This package is up to date.
[INFO] (utf8proc) This package is up to date.
[INFO] (utf8tobibtex) This package is up to date.
[INFO] (utf9) This package is up to date.
[INFO] (utfhate) This package is up to date.
[INFO] (utflib) Data has been updated for this package.
[INFO] (utg) Data has been updated for this package.
[INFO] (uth) This package is up to date.
[INFO] (uthreads) This package is up to date.
[INFO] (uti) This package is up to date.
[INFO] (utide) Data has been updated for this package.
[INFO] (utidylib) Data has been updated for this package.
[INFO] (utify) Data has been updated for this package.
[ERROR] (util) This package does not have downloadable releases.
[INFO] (util-ds) Data has been updated for this package.
[INFO] (util-func) This package is up to date.
[INFO] (util-q) This package is up to date.
[INFO] (util-random) This package is up to date.
[INFO] (utila) This package is up to date.
[INFO] (utilbox) This package is up to date.
[INFO] (utilex) This package is up to date.
[INFO] (utili) This package is up to date.
[INFO] (utilib) This package is up to date.
[INFO] (utilinaut) This package is up to date.
[INFO] (utilio) Data has been updated for this package.
[INFO] (utilis) This package is up to date.
[ERROR] (utilitarian) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (utilitarian-collector) This package is up to date.
[INFO] (utilitarian-queue-consumer) This package is up to date.
[ERROR] (utilities) This package does not have downloadable releases.
[INFO] (utilities-package) This package is up to date.
[INFO] (utilitime) This package is up to date.
[INFO] (utility) This package is up to date.
[INFO] (utility-helper) This package is up to date.
[INFO] (utility-python-script) Data has been updated for this package.
[INFO] (utilitybelt) This package is up to date.
[INFO] (utilityhelper) Data has been updated for this package.
[INFO] (utilize) This package is up to date.
[INFO] (utilkit) This package is up to date.
[INFO] (utillib) This package is up to date.
[INFO] (utilofies) This package is up to date.
[INFO] (utilp) This package is up to date.
[INFO] (utilpy) This package is up to date.
[INFO] (utils) Data has been updated for this package.
[INFO] (utils-config) Data has been updated for this package.
[INFO] (utils-core) Data has been updated for this package.
[INFO] (utils-django) Data has been updated for this package.
[INFO] (utils-fei) Data has been updated for this package.
[INFO] (utils-flask-sqlalchemy) Data has been updated for this package.
[INFO] (utils-gao) This package is up to date.
[INFO] (utils-mini) Data has been updated for this package.
[INFO] (utils-misc) Data has been updated for this package.
[INFO] (utils-py) This package is up to date.
[INFO] (utils2) This package is up to date.
[INFO] (utils2devops) This package is up to date.
[INFO] (utilscell) Data has been updated for this package.
[INFO] (utilsfunc) Data has been updated for this package.
[INFO] (utilspie) This package is up to date.
[INFO] (utilspy) This package is up to date.
[INFO] (utilsuneed) This package is up to date.
[INFO] (utiltest) This package is up to date.
[ERROR] (utiltest-e) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (utilthreading) This package is up to date.
[INFO] (utiltools) This package is up to date.
[INFO] (utilx) Data has been updated for this package.
[INFO] (utilz) This package is up to date.
[INFO] (utinypass) This package is up to date.
[INFO] (utipy) This package is up to date.
[INFO] (utknows) This package is up to date.
[INFO] (utl) This package is up to date.
[ERROR] (utlimate-webshots-converter-for-kde) Could not extract data from this package. See below for details.
".php" extension not supported.
[INFO] (utlts) This package is up to date.
[INFO] (utlz) This package is up to date.
[INFO] (utm) This package is up to date.
[INFO] (utm-zone) Data has been updated for this package.
[INFO] (utmcon) This package is up to date.
[INFO] (utmp) This package is up to date.
[INFO] (utool) Data has been updated for this package.
[INFO] (utoolbox) Data has been updated for this package.
[INFO] (utools) This package is up to date.
[INFO] (utools-dev) This package is up to date.
[ERROR] (utopia) This package does not have downloadable releases.
[INFO] (utopia-cli) This package is up to date.
[INFO] (utopian) This package is up to date.
[INFO] (utopian-api) This package is up to date.
[INFO] (utopy) This package is up to date.
[INFO] (utorrent-py) This package is up to date.
[ERROR] (utrahash) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (utrme) This package is up to date.
[INFO] (utrunner) Data has been updated for this package.
[INFO] (uts) This package is up to date.
[INFO] (utsessions) This package is up to date.
[INFO] (utt) Data has been updated for this package.
[INFO] (utter) This package is up to date.
[INFO] (utter-more) This package is up to date.
[INFO] (utterson) This package is up to date.
[INFO] (uttt) This package is up to date.
[INFO] (uttt-irc) This package is up to date.
[INFO] (uttut) This package is up to date.
[ERROR] (utube) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (utuby) This package is up to date.
[INFO] (utvsapitoken) This package is up to date.
[INFO] (utwist) This package is up to date.
[INFO] (utyls) This package is up to date.
[INFO] (uu-fibonacci) This package is up to date.
[INFO] (uu-game-of-life) This package is up to date.
[ERROR] (uudelens) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "http://www.florian-diesch.de/software/uudelens/"
[INFO] (uuid) This package is up to date.
[INFO] (uuid-shortener-py) This package is up to date.
[INFO] (uuid0) This package is up to date.
[INFO] (uuid1) This package is up to date.
[INFO] (uuid64) This package is up to date.
[INFO] (uule-grabber) This package is up to date.
[INFO] (uulm-mensa) This package is up to date.
[INFO] (uuo) Data has been updated for this package.
[ERROR] (uv) This package does not have downloadable releases.
[INFO] (uva-jhub-cas-authenticator) This package is up to date.
[INFO] (uva-jupyterhub) This package is up to date.
[INFO] (uva-notebook) This package is up to date.
[INFO] (uva-questions) This package is up to date.
[INFO] (uva-swarmspawner) This package is up to date.
[INFO] (uvalde) This package is up to date.
[INFO] (uvarint) Data has been updated for this package.
[INFO] (uvc) This package is up to date.
[INFO] (uvc-content) This package is up to date.
[INFO] (uvcclient) This package is up to date.
[INFO] (uvhttp) This package is up to date.
[INFO] (uvhue) This package is up to date.
[INFO] (uvicorn) Data has been updated for this package.
[INFO] (uvincenty) This package is up to date.
[INFO] (uvio) This package is up to date.
[INFO] (uvitools) This package is up to date.
[INFO] (uvkpy) Data has been updated for this package.
[INFO] (uvloop) Data has been updated for this package.
[INFO] (uvml) This package is up to date.
[INFO] (uvoauth) This package is up to date.
[INFO] (uvp-adb) This package is up to date.
[INFO] (uvplot) Data has been updated for this package.
[INFO] (uvpool) Data has been updated for this package.
[INFO] (uvpool-web) Data has been updated for this package.
[ERROR] (uvs-utils) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (uvsc) This package is up to date.
[INFO] (uvsnap) This package is up to date.
[INFO] (uvspotify) This package is up to date.
[INFO] (uvsq-theme) This package is up to date.
[INFO] (uvtextureconverter) Data has been updated for this package.
[INFO] (uvtor) This package is up to date.
[INFO] (uvvispy) Data has been updated for this package.
[INFO] (uvw) This package is up to date.
[INFO] (uvwsgi) This package is up to date.
[INFO] (uvwxyz) This package is up to date.
[INFO] (uw-atg-wx) This package is up to date.
[INFO] (uw-canvas-users-lti) This package is up to date.
[INFO] (uw-course-roster-lti) This package is up to date.
[INFO] (uw-django-saml2) Data has been updated for this package.
[INFO] (uw-ems-client) This package is up to date.
[INFO] (uw-grade-conversion-calculator) This package is up to date.
[INFO] (uw-grading-standard-lti) This package is up to date.
[INFO] (uw-groups-lti) This package is up to date.
[INFO] (uw-highp-geophysics-tools) Data has been updated for this package.
[INFO] (uw-hx-toolkit) Data has been updated for this package.
[INFO] (uw-iam-resttools) Data has been updated for this package.
[INFO] (uw-library-guides-lti) This package is up to date.
[INFO] (uw-panopto-client) This package is up to date.
[INFO] (uw-restclients) This package is up to date.
[INFO] (uw-restclients-adsel) Data has been updated for this package.
[INFO] (uw-restclients-bookstore) Data has been updated for this package.
[INFO] (uw-restclients-bridge) Data has been updated for this package.
[INFO] (uw-restclients-canvas) Data has been updated for this package.
[INFO] (uw-restclients-catalyst) This package is up to date.
[INFO] (uw-restclients-coda) This package is up to date.
[INFO] (uw-restclients-core) Data has been updated for this package.
[INFO] (uw-restclients-django-utils) Data has been updated for this package.
[INFO] (uw-restclients-grad) This package is up to date.
[INFO] (uw-restclients-gradepage) This package is up to date.
[INFO] (uw-restclients-graderoster) Data has been updated for this package.
[INFO] (uw-restclients-gws) Data has been updated for this package.
[INFO] (uw-restclients-hfs) This package is up to date.
[INFO] (uw-restclients-hrp) Data has been updated for this package.
[INFO] (uw-restclients-iasystem) Data has been updated for this package.
[INFO] (uw-restclients-kws) Data has been updated for this package.
[INFO] (uw-restclients-libraries) This package is up to date.
[INFO] (uw-restclients-mailman) This package is up to date.
[INFO] (uw-restclients-myplan) This package is up to date.
[INFO] (uw-restclients-nws) Data has been updated for this package.
[INFO] (uw-restclients-pws) Data has been updated for this package.
[INFO] (uw-restclients-r25) This package is up to date.
[INFO] (uw-restclients-sdbmyuw) This package is up to date.
[INFO] (uw-restclients-sws) Data has been updated for this package.
[INFO] (uw-restclients-trumba) Data has been updated for this package.
[INFO] (uw-restclients-upass) This package is up to date.
[INFO] (uw-restclients-uwnetid) Data has been updated for this package.
[INFO] (uw-restclients-wheniwork) This package is up to date.
[INFO] (uw-restclients-zoom) Data has been updated for this package.
[INFO] (uw-saml) Data has been updated for this package.
[INFO] (uw-tools) This package is up to date.
[INFO] (uw-webdriver-recorder) Data has been updated for this package.
[INFO] (uwallet) This package is up to date.
[INFO] (uwaterloo-addcourse) This package is up to date.
[INFO] (uwaterlooapi) This package is up to date.
[INFO] (uwaterloodriver) This package is up to date.
[INFO] (uweb) This package is up to date.
[INFO] (uwebsockets) This package is up to date.
[INFO] (uwg) This package is up to date.
[INFO] (uwgeodynamics) Data has been updated for this package.
[INFO] (uwgs) This package is up to date.
[INFO] (uwhoisd) This package is up to date.
[INFO] (uwigopigo) This package is up to date.
[INFO] (uwkm-streamfields) This package is up to date.
[INFO] (uwl) This package is up to date.
[INFO] (uwocalendar) This package is up to date.
[INFO] (uwosh-atimageeditor) This package is up to date.
[INFO] (uwosh-default) This package is up to date.
[INFO] (uwosh-double-blind-review) This package is up to date.
[INFO] (uwosh-meeting) This package is up to date.
[INFO] (uwosh-northstar) This package is up to date.
[INFO] (uwosh-oie-studyabroadtheme) Data has been updated for this package.
[INFO] (uwosh-pfg-d2c) This package is up to date.
[INFO] (uwosh-portaltabssearchbox) This package is up to date.
[INFO] (uwosh-simpleemergency) This package is up to date.
[INFO] (uwosh-snippets) This package is up to date.
[INFO] (uwosh-timeslot) This package is up to date.
[INFO] (uwosh-transitionbuttons) This package is up to date.
[INFO] (uwrit-rit-pypi) This package is up to date.
[INFO] (uws-client) This package is up to date.
[INFO] (uwsgi) This package is up to date.
[INFO] (uwsgi-cache) This package is up to date.
[INFO] (uwsgi-cli) This package is up to date.
[INFO] (uwsgi-cloudwatch) This package is up to date.
[INFO] (uwsgi-env) This package is up to date.
[INFO] (uwsgi-exporter) This package is up to date.
[INFO] (uwsgi-manager) This package is up to date.
[INFO] (uwsgi-metrics) This package is up to date.
[INFO] (uwsgi-metrics3) This package is up to date.
[INFO] (uwsgi-pipenv) This package is up to date.
[INFO] (uwsgi-sloth) This package is up to date.
[INFO] (uwsgi-stub) This package is up to date.
[INFO] (uwsgi-tasks) This package is up to date.
[INFO] (uwsgi-tools) This package is up to date.
[INFO] (uwsgicachetop) This package is up to date.
[INFO] (uwsgiconf) Data has been updated for this package.
[INFO] (uwsgidecorators) This package is up to date.
[INFO] (uwsgidecorators-fallback) This package is up to date.
[INFO] (uwsgidns) This package is up to date.
[INFO] (uwsgifouine) This package is up to date.
[INFO] (uwsgiit-console) This package is up to date.
[INFO] (uwsgiit-py) This package is up to date.
[INFO] (uwsgitop) This package is up to date.
[INFO] (uwsgiwebtop) This package is up to date.
[INFO] (uwsift) Data has been updated for this package.
[INFO] (uwstyle) Data has been updated for this package.
[INFO] (uwtools) Data has been updated for this package.
[INFO] (uwu) This package is up to date.
[INFO] (uwygtfvjha) This package is up to date.
[INFO] (ux) Data has been updated for this package.
[INFO] (uxadt) This package is up to date.
[INFO] (uxapi) Data has been updated for this package.
[INFO] (uxbgtk) This package is up to date.
[INFO] (uxml) This package is up to date.
[INFO] (uxml2object) This package is up to date.
[INFO] (uxsdcxx) Data has been updated for this package.
[INFO] (uz) This package is up to date.
[INFO] (uz-sdk) This package is up to date.
[INFO] (uzentropi) This package is up to date.
[INFO] (uzkchemtem) This package is up to date.
[INFO] (uzless-decorator) Data has been updated for this package.
[INFO] (uzmq) This package is up to date.
[INFO] (uzu-accounts-app) Data has been updated for this package.
[INFO] 
[INFO] 
[INFO] Total packages: 2320
[INFO]     Packages processed: 2320
[INFO]         Packages updated: 594
[INFO]         Packages up-to-date: 1597
[INFO]         Packages without response: 41
[INFO]         Packages without urls: 0
[INFO]         Packages without downloads: 65
[INFO]         Packages with data errors: 23
[INFO]     Packages not processed: 0
[INFO] 
[INFO] 
[INFO] Ending execution.
